In [2]:
setwd("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex")

source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/code/enrichment_fxns.R")
source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/code/gene_mapping_fxns.R")
source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/code/top_corr_module_fxns.R")

Here I perform enrichment analysis to find modules enriched for cell type markers. 

These modules will later be used to correlate with exon PSI to define cell type-specific exons.

In [1]:
n_workers <- 20

In [ ]:
mod_def <- "PosBC"

In [ ]:
max_set_size <- 200
min_set_size <- 3

## Prep marker genes

### Claude marker genes

In [3]:
set_source <- "Claude_marker_genes"

marker_genes_list <- readRDS("/mnt/lareaulab/reliscu/projects/NSF_GRFP/data/marker_genes/AI/Claude_cortical_markers_human.RDS")

### Broad

In [ ]:
library(msigdbr)

In [ ]:
gs_GOBP <- msigdbr(collection="C5", subcollection="GO:BP")

gs_CTS <- msigdbr(collection="C8")
gs_CTS <- gs_CTS[gs_CTS$gs_geoid == "GSE104276",]

gs_GOBP_list <- tapply(gs_GOBP$gene_symbol, INDEX=gs_GOBP$gs_name, FUN=list)
gs_CTS_list <- tapply(gs_CTS$gene_symbol, INDEX=gs_CTS$gs_name, FUN=list)

gs_list <- c(gs_GOBP_list, gs_CTS_list)

In [ ]:
set_sizes <- lengths(gs_list)
mask <- (set_sizes < max_set_size) & (set_sizes > min_set_size)
gs_list <- gs_list[mask]

print(length(gs_list))

In [ ]:
set_source <- paste0("MSigDB_", length(gs_list), "sets")

### MO marker genes

In [ ]:
load("/mnt/lareaulab/reliscu/data/gene_sets/Oldham/MO_sets.RData")

names(marker_genes_list) <- MO_legend$SetName

mask <- !MO_legend$Category %in% "Disease"
marker_genes_list <- MO_sets[mask]

In [ ]:
set_sizes <- lengths(marker_genes_list)
mask <- (set_sizes < max_set_size) & (set_sizes > min_set_size)
marker_genes_list <- marker_genes_list[mask]

print(length(marker_genes_list))

In [ ]:
set_source <- paste0("MO_", length(marker_genes_list), "sets")

## Get enrichments

In [37]:
network_dir <- "GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules"

In [ ]:
enrichments_df <- get_module_enrichments_par(network_dir, marker_genes_list, mod_def, n_workers)

In [39]:
# Get most enriched cell type for each module
# If cell type is most enriched in multiple modules, choose module with smallest p-value

top_mods_df <- enrichments_df %>%
    group_by(Cell_type) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    group_by(Network, Module) %>%
    arrange(Network) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    arrange(Qval)

In [40]:
top_mods_df[,c("Cell_type", "Pval", "Qval", "Module", "Network")]

   Cell_type         Pval         Qval         Module
1  Micro/PVM         9.079137e-24 4.398842e-19 plum1
2  Astro             4.074082e-18 4.386429e-14 khaki3
3  Oligo             5.203321e-18 5.042018e-14 darkgrey
4  All GABAergic     1.161883e-17 1.023514e-13 steelblue
5  VLMC              1.478217e-12 4.939285e-09 thistle3
6  Sst               1.108788e-10 2.387589e-07 greenyellow
7  Endo              4.700871e-10 9.110287e-07 seagreen4
8  Vip               7.647361e-09 9.880391e-06 magenta1
9  OPC               2.159819e-08 2.491505e-05 orangered4
10 Sst Chodl         9.384499e-08 9.003544e-05 darkmagenta
11 All Neuronal      1.349181e-07 1.245101e-04 lightsteelblue1
12 CGE Class         2.309374e-07 1.998021e-04 skyblue4
13 L2/3 IT           7.599718e-07 5.149739e-04 greenyellow
14 Peri              1.378624e-06 8.731282e-04 midnightblue
15 Sncg              4.400662e-06 2.395641e-03 darkturquoise
16 All Glutamatergic 4.556119e-06 2.466413e-03 blue
17 L5 IT             1.146716e-05 5.420330e-03 paleturquoise1
18 L5/6 NP           1.783400e-05 7.819521e-03 lightpink3
19 L6b               2.138116e-05 8.929619e-03 brown2
20 L5 ET             3.898106e-05 1.464056e-02 thistle1
21 L6 IT             5.692204e-05 1.929593e-02 indianred
22 L4 IT             8.144365e-05 2.537585e-02 firebrick4
23 L6 CT             1.405631e-04 3.881228e-02 thistle
24 Lamp5             2.106868e-04 5.358411e-02 greenyellow
25 Chandelier        2.055906e-03 3.399612e-01 darkgoldenrod4
26 L6 IT Car3        3.839563e-03 5.612344e-01 lightskyblue4
   Network
1  Bicor-None_signum0.781_minSize10_merge_ME_0.95_22162
2  Bicor-None_signum0.881_minSize3_merge_ME_0.95_22162
3  Bicor-None_signum0.663_minSize8_merge_ME_0.95_22162
4  Bicor-None_signum0.881_minSize4_merge_ME_0.95_22162
5  Bicor-None_signum0.731_minSize10_merge_ME_0.95_22162
6  Bicor-None_signum0.953_minSize3_merge_ME_0.95_22162
7  Bicor-None_signum0.693_minSize6_merge_ME_0.95_22162
8  Bicor-None_signum0.881_minSize3_merge_ME_0.95_22162
9  Bicor-None_signum0.928_minSize3_merge_ME_0.95_22162
10 Bicor-None_signum0.928_minSize3_merge_ME_0.95_22162
11 Bicor-None_signum0.693_minSize6_merge_ME_0.95_22162
12 Bicor-None_signum0.781_minSize8_merge_ME_0.95_22162
13 Bicor-None_signum0.928_minSize4_merge_ME_0.95_22162
14 Bicor-None_signum0.928_minSize3_merge_ME_0.95_22162
15 Bicor-None_signum0.881_minSize6_merge_ME_0.95_22162
16 Bicor-None_signum0.881_minSize6_merge_ME_0.95_22162
17 Bicor-None_signum0.663_minSize8_merge_ME_0.95_22162
18 Bicor-None_signum0.663_minSize6_merge_ME_0.95_22162
19 Bicor-None_signum0.781_minSize6_merge_ME_0.95_22162
20 Bicor-None_signum0.781_minSize10_merge_ME_0.95_22162
21 Bicor-None_signum0.693_minSize6_merge_ME_0.95_22162
22 Bicor-None_signum0.731_minSize8_merge_ME_0.95_22162
23 Bicor-None_signum0.693_minSize10_merge_ME_0.95_22162
24 Bicor-None_signum0.881_minSize8_merge_ME_0.95_22162
25 Bicor-None_signum0.881_minSize3_merge_ME_0.95_22162
26 Bicor-None_signum0.663_minSize6_merge_ME_0.95_22162

In [41]:
get_mod_vs_DE_genes(top_mods_df, marker_genes_list, mod_def)

                  Cell_type         Qval
Micro/PVM         Micro/PVM         4.398842e-19
Astro             Astro             4.386429e-14
Oligo             Oligo             5.042018e-14
All GABAergic     All GABAergic     1.023514e-13
VLMC              VLMC              4.939285e-09
Sst               Sst               2.387589e-07
Endo              Endo              9.110287e-07
Vip               Vip               9.880391e-06
OPC               OPC               2.491505e-05
Sst Chodl         Sst Chodl         9.003544e-05
All Neuronal      All Neuronal      1.245101e-04
CGE Class         CGE Class         1.998021e-04
L2/3 IT           L2/3 IT           5.149739e-04
Peri              Peri              8.731282e-04
Sncg              Sncg              2.395641e-03
All Glutamatergic All Glutamatergic 2.466413e-03
L5 IT             L5 IT             5.420330e-03
L5/6 NP           L5/6 NP           7.819521e-03
L6b               L6b               8.929619e-03
L5 ET             L5 ET             1.464056e-02
L6 IT             L6 IT             1.929593e-02
L4 IT             L4 IT             2.537585e-02
L6 CT             L6 CT             3.881228e-02
Lamp5             Lamp5             5.358411e-02
Chandelier        Chandelier        3.399612e-01
L6 IT Car3        L6 IT Car3        5.612344e-01
                  Module_genes
Micro/PVM         LAPTM5, NCKAP1L, CSF1R, TBXAS1, SYK, ITGB2, HAVCR2, IRF8, APBB1IP, SASH3, BTK, DOCK2, TYROBP, C1QA, TLR6
Astro             MSI2, SPON1, PLPP3, METTL7A, BMPR1B, SLC39A12, S1PR1, RANBP3L, HSDL2, SASH1, GLI3, ERLIN2, SDC2, FERMT2, TMBIM6
Oligo             MAG, MOG, CNP, ENPP2, FA2H, GJB1, NINJ2, TMEM125, CLDN11, GPR62, KLK6, GPR37, SLC44A1, DBNDD2, PLLP
All GABAergic     GAD2, ZNF385D, GAD1, NXPH2, VWC2, BTBD11, ARL4C, MYO5B, GJD2, LGI2, KCNS3, NXPH1, KCNAB1, GRK3, GRIP1
VLMC              SLC13A4, FAM20A, DSP, STRA6, SLC5A5, SLC6A20, SERPIND1, PTGDR, INSRR, FMOD, MLPH, WNK4, SLC9A2, DSG2, BNC2
Sst               GAD2, GAD1, ZNF385D, NXPH2, MYO5B, BTBD11, LGI2, NXPH1, VWC2, KCNS3, ARL4C, DLX6, MINAR1, TAC1, GRIP1
Endo              ESAM, PRKCH, MECOM, CLEC14A, LSR, PTPRB, CD34, PAQR5, SHE, GATA2, MMRN2, PALMD, SLC2A1, LEF1, ABCB1
Vip               DLX1, DLX6-AS1, PRLHR, CNR1, GAD2, RGS8, DLX2, DLX5, DLX6, GRIK1, HAPLN1, BTBD11, GAD1, SP8, KIT
OPC               MBP, TP53INP2, MOBP, BCAS1, PAQR6, PAIP2B, CTNNA3, LPAR1, MTURN, PTP4A2, MAP4K4, KIF1C, HIPK2, PKP4, SHTN1
Sst Chodl         GAD2, GAD1, ZNF385D, NXPH2, MYO5B, BTBD11, LGI2, NXPH1, VWC2, KCNS3, ARL4C, DLX6, MINAR1, TAC1, GRIP1
All Neuronal      TMEM59L, DNM1, ATP6V0A1, FBXO44, APBA2, GDI1, GPI, CACNB1, ATP6V0C, GPR162, PRKAR1B, SLC22A17, GSK3A, ARMC6, TWF2
CGE Class         DLX1, DLX6-AS1, PRLHR, DLX2, DLX5, RGS8, GRIK1, TAC3, CNR1, DLX6, BTBD11, ENSG00000277954, PTHLH, GAD2, GAD1
L2/3 IT           DPP6, GRIN2B, TMEM178B, PTPRO, KIAA1549L, DLG3, RBFOX2, TMEM132D, CHRM3, LRRTM4, FRMPD4, PAK1, LNX1, RAB6B, SLC12A5
Peri              MYL9, ACTA2, MYH11, AOC3, CNN1, ITIH3, KCNMB1, TAGLN, JPH2, TPM2, FLNA, COL8A1, SUSD2, COL14A1, CASQ2
Sncg              GAD2, ZNF385D, GAD1, NXPH2, VWC2, BTBD11, ARL4C, MYO5B, GJD2, LGI2, KCNS3, NXPH1, KCNAB1, GRK3, GRIP1
All Glutamatergic RTN1, FAXC, ATP6V1C1, MOAP1, BTBD10, SLC25A4, ATP6V1B2, NDRG3, NSF, PAK1, MAP7D2, CLCN4, NMNAT2, GOT1, GNB5
L5 IT             YPEL2, GNAI1, CLASP2, LPGAT1, LANCL1, STK39, LDLRAD4, USP32, VAPB, NCOA7, DNM3, ADSS2, DNAJC6, STAM, ANK3
L5/6 NP           NXPH1, GLRA2, GAD1, GAD2, MINAR1, TAC1, KLHL13, ANKRD50, PLD5, FSTL5, SP9, CRHBP, HTR2C, GNG2, PKIB
L6b               DLG4, SEPTIN5, JPH4, SYNPO, PAK6, SOBP, DLGAP3, AMPD2, AGAP2, SPTBN2, PACSIN1, FBXO41, NEURL1, CBX6, JPH3
L5 ET             GABRA3, PLPPR4, SHISA9, GDA, SEZ6L, GRM1, ROBO2, FRRS1L, PGM2L1, VXN, PAK3, TUSC3, DGKB, KCTD16, ACTR3B
L6 IT             CNIH3, RASGRP1, CPNE4, NRG1, DCLK1, SULT4A1, DIRAS2, SMIM43, NUAK1, KIFAP3, GOT1, MAP1B, SMYD2, PCLO, MOAP1
L4 IT             TESPA1, CBLN2, LRATD1, LRFN5, NLK, KCTD1, EPHX4, FAM234B, FBXO34, KCNB1, HTR5A, SLC12A5, SDR16C5, PREP, ABLIM2
L6 CT             NXPH1, GLRA2, GAD1, GAD2, TAC1, MINAR1, ANKRD50, FSTL5, KLHL13, PLD5, CRHBP, SP9, ZNF385D, PKIB, NXPH2
Lamp5             DPP6, KIAA1549L, LRRTM4, TMEM178B, UNC5D, CHRM3, GRIN2B, NDST3, PTPRO, C11orf87, FRMPD4, TMEM132D, RBFOX2, SLC12A5, LNX1
Chandelier        ZER1, VAC14, CPNE5, RUSC2, AP2A2, MAPK8IP3, IP6K1, ATP13A2, KATNB1, AP2A1, DHX30, MAPT, MAP6, CPT1C, TBC1D25
L6 IT Car3        PLD5, DLX1, HAPLN1, TOX3, CNR1, PTHLH, KIT, NXPH1, DAB1, DLX6-AS1, KCNMB2, GAD2, GAD1, GRIK1, VIP
                  DE_genes
Micro/PVM         CTSS, CX3CR1, ITGAM, P2RY12, TMEM119, TYROBP, AIF1, C1QA, C1QB, C1QC, CSF1R, HEXB, SALL1, SPI1, TREM2
Astro             ALDH1L1, AQP4, GFAP, SLC1A2, SLC1A3, ALDOC, FGFR3, GJA1, GLUL, NDRG2, S100B, SOX9, ACSL6, AGT, APOE
Oligo             MBP, MOG, PLP1, CLDN11, CNP, ERMN, MAG, MOBP, OPALIN, ENPP6, FA2H, KLK6, TF, UGT8A, NA
All GABAergic     GAD1, GAD2, SLC32A1, DLX1, DLX2, DLX5, DLX6, NA, NA, NA, NA, NA, NA, NA, NA
VLMC              COL1A1, COL1A2, DCN, LUM, CD44, COL3A1, IL33, OGN, PTGDS, SLC6A13, SPP1, NA, NA, NA, NA
Sst               SST, CALB1, CALB2, CBLN4, CHRNA2, ETV1, HPSE, MYH8, NPY, TH, RELN, NA, NA, NA, NA
Endo              CLDN5, FLT1, EMCN, NOSTRIN, PECAM1, SLCO1A4, TEK, VWF, BSG, ITM2A, LY6C1, NA, NA, NA, NA
Vip               VIP, CALB2, CHAT, CRH, GPC3, MYBPC1, TAC3, NA, NA, NA, NA, NA, NA, NA, NA
OPC               CSPG4, PDGFRA, GPR17, NKX2-2, OLIG1, OLIG2, SOX10, VCAN, BCAN, PCDH15, PTPRZ1, NA, NA, NA, NA
Sst Chodl         CHODL, SST, NOS1, NPY, TACR1, MME, NA, NA, NA, NA, NA, NA, NA, NA, NA
All Neuronal      RBFOX3, MAP2, SNAP25, SYT1, TUBB3, ENO2, NRGN, STMN2, THY1, NA, NA, NA, NA, NA, NA
CGE Class         ADARB2, NR2F2, PROX1, HTR3A, SP8, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
L2/3 IT           CUX2, LINC00507, CUX1, MDGA1, OTOF, RASGRF2, LAMP5, NA, NA, NA, NA, NA, NA, NA, NA
Peri              ABCC9, KCNJ8, PDGFRB, ANPEP, CSPG4, MCAM, NOTCH3, RGS5, VTN, DES, DLK1, NA, NA, NA, NA
Sncg              SNCG, CALB2, CCK, CNR1, NPY2R, PENK, NA, NA, NA, NA, NA, NA, NA, NA, NA
All Glutamatergic SLC17A7, CAMK2A, SATB2, SLC17A6, TBR1, EMX1, NEUROD2, NEUROD6, NA, NA, NA, NA, NA, NA, NA
L5 IT             DEPTOR, THEMIS, BATF3, HSD11B1, PDE1C, TCERG1L, NA, NA, NA, NA, NA, NA, NA, NA, NA
L5/6 NP           TRHR, TSHZ2, HTR2C, NXPH4, SERPINE2, SLC17A8, NA, NA, NA, NA, NA, NA, NA, NA, NA
L6b               CCN2, NXPH4, CPLX3, INPP4B, OR2T8, RGS12, SERPINB11, TRH, NA, NA, NA, NA, NA, NA, NA
L5 ET             BCL11B, BCL6, FAM84B, FEZF2, CDH13, CHRNA6, CRYM, NNAT, NPNT, POU3F1, NA, NA, NA, NA, NA
L6 IT             FOXP2, OPRK1, SLA, THEMIS, ZNF804B, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
L4 IT             RORB, RSPO1, COL5A2, CTXN3, THSD7A, WHRN, NA, NA, NA, NA, NA, NA, NA, NA, NA
L6 CT             FOXP2, SYT6, NTNG2, NXPH2, TLE4, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
Lamp5             LAMP5, DOCK5, LCP2, LSP1, NDNF, NTN1, PLCH2, RELN, NA, NA, NA, NA, NA, NA, NA
Chandelier        PVALB, UNC5B, VIPR2, CPNE5, NOS1, SNHG14, NA, NA, NA, NA, NA, NA, NA, NA, NA
L6 IT Car3        CA3, LXN, NR2F2, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
                  Intersection_genes
Micro/PVM         CTSS,CX3CR1,ITGAM,P2RY12,TMEM119,TYROBP,AIF1,C1QA,C1QB,C1QC,CSF1R,SPI1,TREM2,SELPLG
Astro             AQP4,SLC1A2,SLC1A3,FGFR3,GJA1,GLUL,SOX9,AGT,APOE
Oligo             MOG,PLP1,CLDN11,CNP,ERMN,MAG,OPALIN,FA2H,KLK6,TF
All GABAergic     GAD1,GAD2,SLC32A1,DLX1,DLX5,DLX6
VLMC              COL1A1,COL1A2,DCN,COL3A1,OGN,PTGDS,SLC6A13
Sst               SST,CALB1
Endo              CLDN5,FLT1,EMCN,NOSTRIN,PECAM1,VWF,ITM2A
Vip               VIP,CALB2,CRH,TAC3
OPC               OLIG1,SOX10
Sst Chodl         SST,TACR1
All Neuronal      RBFOX3,TUBB3,NRGN,THY1
CGE Class         HTR3A,SP8
L2/3 IT           RASGRF2
Peri              MCAM,NOTCH3,DES
Sncg              CNR1
All Glutamatergic
L5 IT             DEPTOR
L5/6 NP           HTR2C,SLC17A8
L6b
L5 ET             CDH13
L6 IT
L4 IT
L6 CT             SYT6,NXPH2
Lamp5
Chandelier        CPNE5
L6 IT Car3
                  Module
Micro/PVM         plum1
Astro             khaki3
Oligo             darkgrey
All GABAergic     steelblue
VLMC              thistle3
Sst               greenyellow
Endo              seagreen4
Vip               magenta1
OPC               orangered4
Sst Chodl         darkmagenta
All Neuronal      lightsteelblue1
CGE Class         skyblue4
L2/3 IT           greenyellow
Peri              midnightblue
Sncg              darkturquoise
All Glutamatergic blue
L5 IT             paleturquoise1
L5/6 NP           lightpink3
L6b               brown2
L5 ET             thistle1
L6 IT             indianred
L4 IT             firebrick4
L6 CT             thistle
Lamp5             greenyellow
Chandelier        darkgoldenrod4
L6 IT Car3        lightskyblue4
                  Network
Micro/PVM         Bicor-None_signum0.781_minSize10_merge_ME_0.95_22162
Astro             Bicor-None_signum0.881_minSize3_merge_ME_0.95_22162
Oligo             Bicor-None_signum0.663_minSize8_merge_ME_0.95_22162
All GABAergic     Bicor-None_signum0.881_minSize4_merge_ME_0.95_22162
VLMC              Bicor-None_signum0.731_minSize10_merge_ME_0.95_22162
Sst               Bicor-None_signum0.953_minSize3_merge_ME_0.95_22162
Endo              Bicor-None_signum0.693_minSize6_merge_ME_0.95_22162
Vip               Bicor-None_signum0.881_minSize3_merge_ME_0.95_22162
OPC               Bicor-None_signum0.928_minSize3_merge_ME_0.95_22162
Sst Chodl         Bicor-None_signum0.928_minSize3_merge_ME_0.95_22162
All Neuronal      Bicor-None_signum0.693_minSize6_merge_ME_0.95_22162
CGE Class         Bicor-None_signum0.781_minSize8_merge_ME_0.95_22162
L2/3 IT           Bicor-None_signum0.928_minSize4_merge_ME_0.95_22162
Peri              Bicor-None_signum0.928_minSize3_merge_ME_0.95_22162
Sncg              Bicor-None_signum0.881_minSize6_merge_ME_0.95_22162
All Glutamatergic Bicor-None_signum0.881_minSize6_merge_ME_0.95_22162
L5 IT             Bicor-None_signum0.663_minSize8_merge_ME_0.95_22162
L5/6 NP           Bicor-None_signum0.663_minSize6_merge_ME_0.95_22162
L6b               Bicor-None_signum0.781_minSize6_merge_ME_0.95_22162
L5 ET             Bicor-None_signum0.781_minSize10_merge_ME_0.95_22162
L6 IT             Bicor-None_signum0.693_minSize6_merge_ME_0.95_22162
L4 IT             Bicor-None_signum0.731_minSize8_merge_ME_0.95_22162
L6 CT             Bicor-None_signum0.693_minSize10_merge_ME_0.95_22162
Lamp5             Bicor-None_signum0.881_minSize8_merge_ME_0.95_22162
Chandelier        Bicor-None_signum0.881_minSize3_merge_ME_0.95_22162
L6 IT Car3        Bicor-None_signum0.663_minSize6_merge_ME_0.95_22162
                  ME_path
Micro/PVM         /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.781_minSize10_merge_ME_0.95_22162/Module_eigengenes_10-12-54.csv
Astro             /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.881_minSize3_merge_ME_0.95_22162/Module_eigengenes_09-28-47.csv
Oligo             /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.663_minSize8_merge_ME_0.95_22162/Module_eigengenes_12-54-38.csv
All GABAergic     /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.881_minSize4_merge_ME_0.95_22162/Module_eigengenes_09-43-29.csv
VLMC              /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.731_minSize10_merge_ME_0.95_22162/Module_eigengenes_10-53-41.csv
Sst               /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.953_minSize3_merge_ME_0.95_22162/Module_eigengenes_09-21-13.csv
Endo              /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.693_minSize6_merge_ME_0.95_22162/Module_eigengenes_11-01-47.csv
Vip               /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.881_minSize3_merge_ME_0.95_22162/Module_eigengenes_09-28-47.csv
OPC               /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.928_minSize3_merge_ME_0.95_22162/Module_eigengenes_09-23-17.csv
Sst Chodl         /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.928_minSize3_merge_ME_0.95_22162/Module_eigengenes_09-23-17.csv
All Neuronal      /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.693_minSize6_merge_ME_0.95_22162/Module_eigengenes_11-01-47.csv
CGE Class         /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.781_minSize8_merge_ME_0.95_22162/Module_eigengenes_10-06-10.csv
L2/3 IT           /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.928_minSize4_merge_ME_0.95_22162/Module_eigengenes_09-25-54.csv
Peri              /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.928_minSize3_merge_ME_0.95_22162/Module_eigengenes_09-23-17.csv
Sncg              /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.881_minSize6_merge_ME_0.95_22162/Module_eigengenes_09-49-24.csv
All Glutamatergic /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.881_minSize6_merge_ME_0.95_22162/Module_eigengenes_09-49-24.csv
L5 IT             /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.663_minSize8_merge_ME_0.95_22162/Module_eigengenes_12-54-38.csv
L5/6 NP           /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.663_minSize6_merge_ME_0.95_22162/Module_eigengenes_12-08-28.csv
L6b               /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.781_minSize6_merge_ME_0.95_22162/Module_eigengenes_09-53-27.csv
L5 ET             /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.781_minSize10_merge_ME_0.95_22162/Module_eigengenes_10-12-54.csv
L6 IT             /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.693_minSize6_merge_ME_0.95_22162/Module_eigengenes_11-01-47.csv
L4 IT             /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.731_minSize8_merge_ME_0.95_22162/Module_eigengenes_10-39-01.csv
L6 CT             /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.693_minSize10_merge_ME_0.95_22162/Module_eigengenes_11-55-12.csv
Lamp5             /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.881_minSize8_merge_ME_0.95_22162/Module_eigengenes_09-51-24.csv
Chandelier        /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.881_minSize3_merge_ME_0.95_22162/Module_eigengenes_09-28-47.csv
L6 IT Car3        /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.663_minSize6_merge_ME_0.95_22162/Module_eigengenes_12-08-28.csv
                  kME_path
Micro/PVM         /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.781_minSize10_merge_ME_0.95_22162/kME_table_10-12-54.csv
Astro             /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.881_minSize3_merge_ME_0.95_22162/kME_table_09-28-47.csv
Oligo             /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.663_minSize8_merge_ME_0.95_22162/kME_table_12-54-38.csv
All GABAergic     /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.881_minSize4_merge_ME_0.95_22162/kME_table_09-43-29.csv
VLMC              /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.731_minSize10_merge_ME_0.95_22162/kME_table_10-53-41.csv
Sst               /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.953_minSize3_merge_ME_0.95_22162/kME_table_09-21-13.csv
Endo              /mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/GTEx/cortex/GTEx_cortex_counts_All_501_outliers_removed_ComBat_SMGEBTCH_corrected_mergeParam0.95_subsetCutoff0.002_Modules/Bicor-None_signum0.693_minSize6_merge_ME_0.95_22162/kME_table_11-01-47.csv

In [42]:
write.csv(top_mods_df, file=paste0("data/enrichments/", network_dir, "_", set_source, "_enrichments.csv"), row.names=FALSE, quote=FALSE)

## Compare enrichments

In [ ]:
# x <- list.files("data/enrichments")[grep(set_source, list.files("data/enrichments"))]

# enrichments_list <- lapply(x, function(y) {
#     split <- unlist(strsplit(y, "STAR_"))
#     prefix <- unlist(strsplit(split[1], "_ComBat"))[1]
#     middle <- gsub("p_", "p", unlist(strsplit(split[1], "yao_2021_"))[2])
#     suffix <- gsub("_enrichments.csv", "", unlist(strsplit(split[2], "DE_genes_"))[2])
#     dataname <- paste(prefix, paste(middle, suffix, sep="_"), sep="_")

#     enrich_df <- fread(file.path("data/enrichments", y), data.table=FALSE)
#     enrich_df <- enrich_df[,c("Cell_type", "Qval")]
#     colnames(enrich_df)[2] <- dataname
#     enrich_df
# })

# enrichment_table <- Reduce(f=function(x, y) {
#     merge(x, y, by="Cell_type", all=TRUE)
# }, enrichments_list)

In [ ]:
# enrichment_table

   Cell_type         GTEx_cortex_counts_All_501_outliers_removed_NA_NA
1  All GABAergic     1.023514e-13
2  All Glutamatergic 2.466413e-03
3  All Neuronal      1.245101e-04
4  Astro             4.386429e-14
5  CGE Class         1.998021e-04
6  Chandelier        3.399612e-01
7  Endo              9.110287e-07
8  L2/3 IT           5.149739e-04
9  L4 IT             2.537585e-02
10 L5 ET             1.464056e-02
11 L5 IT             5.420330e-03
12 L5/6 NP           7.819521e-03
13 L6 CT             3.881228e-02
14 L6 IT             1.929593e-02
15 L6 IT Car3        5.612344e-01
16 L6b               8.929619e-03
17 Lamp5             5.358411e-02
18 Lamp5 Lhx6                  NA
19 MGE Class                   NA
20 Micro/PVM         4.398842e-19
21 Oligo             5.042018e-14
22 OPC               2.491505e-05
23 Pax6                        NA
24 Peri              8.731282e-04
25 Sncg              2.395641e-03
26 Sst               2.387589e-07
27 Sst Chodl         9.003544e-05
28 Vip               9.880391e-06
29 VLMC              4.939285e-09
   GTEx_cortex_TPM_All_598_outliers_removed_NA_NA
1  1.351891e-14
2  1.473401e-02
3  5.003005e-04
4  2.015052e-15
5  1.033153e-04
6  1.106190e-01
7  1.827541e-04
8  1.600087e-06
9  1.028264e-03
10 7.894329e-06
11 1.726946e-04
12 2.499663e-04
13 1.138374e-02
14 4.163267e-03
15           NA
16 3.333611e-02
17 5.148755e-02
18 1.248606e-04
19 4.150476e-08
20 1.289199e-19
21 1.871966e-15
22 3.816560e-04
23           NA
24 1.331057e-04
25 2.169227e-04
26 6.938045e-07
27 2.257362e-05
28 9.531653e-08
29 1.016071e-09
   GTEx_cortex_TPM_QN_rd2_All_501_outliers_removed_NA_NA
1  3.077119e-12
2  2.590165e-02
3  6.197873e-02
4  9.045933e-09
5  1.103737e-04
6  1.603232e-01
7  4.395923e-07
8  1.195509e-05
9  4.809219e-01
10 7.150225e-03
11 1.971950e-02
12 4.364836e-02
13 5.930604e-01
14 1.646976e-02
15 3.333242e-02
16           NA
17           NA
18 1.389992e-03
19           NA
20 2.779556e-14
21 2.779556e-14
22 2.715623e-08
23 6.218126e-01
24 7.096907e-05
25           NA
26 3.546197e-03
27 9.841411e-03
28 2.286891e-07
29 9.045933e-09

In [ ]:
# data.frame(colMeans(enrichment_table[,-1], na.rm=TRUE))

                                                      colMeans.enrichment_table....1...na.rm...TRUE.
GTEx_cortex_counts_All_501_outliers_removed_NA_NA     0.041606701
GTEx_cortex_TPM_All_598_outliers_removed_NA_NA        0.008475941
GTEx_cortex_TPM_QN_rd2_All_501_outliers_removed_NA_NA 0.083171611