In [6]:
library(fgsea)
library(msigdbr)
library(data.table)

In [ ]:
# For each cell type, run fgsea on the ranked list of genes from the eigengene corrlelation analysis

In [24]:
psi_corr_df <- fread("data/ctype_exons/exon_PSI_abundance_correlations.csv", data.table=FALSE)

In [25]:
head(psi_corr_df)

  V1                      Gene            CGE Class   All GABAergic
1 ENSG00000292994_other_1 ENSG00000292994 -0.02538085  0.02298857
2 ENSG00000290385_other_1 ENSG00000290385  0.04501582  0.05790350
3 ENSG00000290385_other_2 ENSG00000290385 -0.03530158 -0.02071717
4 ENSG00000290385_other_3 ENSG00000290385  0.07476380  0.07906006
5 ENSG00000290385_other_4 ENSG00000290385  0.07666083  0.08106413
6 ENSG00000293331_other_2 ENSG00000293331 -0.04096509 -0.03345184
  All Neuronal Upper layer glutamatergic Deep layer glutamatergic Oligo
1 -0.01710559  -0.02455248               -0.006376216             -0.080464292
2  0.19277097   0.14419248                0.095084673              0.087563331
3  0.09364029   0.03872922                0.069526472              0.091651676
4  0.07621338   0.03917839                0.037357760             -0.006209385
5  0.24929533   0.20199612                0.100275245             -0.006106974
6 -0.02414973  -0.03649292               -0.034704053              0.053129400
  OPC         Astro        Micro/PVM   VLMC        Endo         Peri
1 -0.03284337 -0.087215140 -0.11959704  0.01551280 -0.055307605 -0.01800986
2 -0.07047729 -0.092307276  0.01446122 -0.06778905  0.009946656 -0.05130794
3 -0.05817518 -0.066205385  0.06337864 -0.01958832  0.044749824 -0.02397202
4 -0.04665804 -0.083934221 -0.03792666 -0.03897636 -0.036870095 -0.05944792
5 -0.18772872 -0.190689864 -0.04125997 -0.11666902 -0.023454812 -0.13617374
6 -0.01556316  0.009481004 -0.03863956  0.04132287  0.051161645  0.02164531

In [ ]:
psi_fdr_df <- fread("data/ctype_exons/exon_PSI_abundance_correlation_FDRs.csv", data.table=FALSE)

In [4]:
head(psi_fdr_df)

  V1                      Gene            CGE Class All GABAergic All Neuronal
1 ENSG00000292994_other_1 ENSG00000292994 0.7541050 0.7623041     0.80293766
2 ENSG00000290385_other_1 ENSG00000290385 0.5385117 0.3602815     0.00000000
3 ENSG00000290385_other_2 ENSG00000290385 0.6448909 0.7876755     0.08399105
4 ENSG00000290385_other_3 ENSG00000290385 0.2494132 0.1879692     0.18075564
5 ENSG00000290385_other_4 ENSG00000290385 0.2348188 0.1737992     0.00000000
6 ENSG00000293331_other_2 ENSG00000293331 0.5946899 0.6540153     0.72895971
  Upper layer glutamatergic Deep layer glutamatergic Oligo     OPC
1 0.736748814               0.9505231                0.2448041 0.7092017
2 0.006432068               0.1263878                0.1962640 0.3262741
3 0.558511421               0.3044408                0.1714592 0.4563505
4 0.569252368               0.6404492                0.9581946 0.5675855
5 0.000000000               0.1013392                0.9568999 0.0000000
6 0.615209091               0.6808462                0.5076893 0.8889765
  Astro     Micro/PVM VLMC       Endo      Peri
1 0.1584404 0.1090602 0.87966817 0.4024086 0.84678834
2 0.1365239 0.9127940 0.34317760 0.9110574 0.50055804
3 0.3101504 0.4867520 0.83439060 0.5217144 0.79098088
4 0.1760145 0.7295491 0.64056874 0.6130801 0.41358561
5 0.0000000 0.6969543 0.05608754 0.7708977 0.01794526
6 0.9265374 0.7373923 0.63219299 0.4755212 0.82683254

In [5]:
tail(psi_fdr_df)

      V1                              Gene   CGE Class   All GABAergic
47053 ENSG00000155962_ProteinCoding_1 CLIC2  0.478105053 0.438720347
47054 ENSG00000155962_other_2         CLIC2  0.000000000 0.000000000
47055 ENSG00000124333_ProteinCoding_1 VAMP7  0.000926886 0.001807837
47056 ENSG00000124333_ProteinCoding_2 VAMP7  0.282227493 0.263350203
47057 ENSG00000124334_ProteinCoding_1 IL9R   0.572517652 0.533235127
47058 ENSG00000182484_ProteinCoding_1 WASH6P 0.576131409 0.925027907
      All Neuronal Upper layer glutamatergic Deep layer glutamatergic Oligo
47053 0.8106383    0.8422904341              0.904970254              0.9991465
47054 0.0000000    0.0000000000              0.003350914              0.9518340
47055 0.0000000    0.0006457802              0.417172515              0.0000000
47056 0.3208426    0.3219879522              0.948209968              0.4211068
47057 0.5747916    0.3588468783              0.735556874              0.9874526
47058 0.7741886    0.4386011095              0.684715814              0.5837527
      OPC       Astro     Micro/PVM VLMC        Endo        Peri
47053 0.1198352 0.4088309 0.3529932 0.415094534 0.081752356 0.418783660
47054 0.2852928 0.0000000 0.8154515 0.007931124 0.003763436 0.017397959
47055 0.0000000 0.0000000 0.5709718 0.021477864 0.003109731 0.001062257
47056 0.8661951 0.0637925 0.9451811 0.610766867 0.429751720 0.809902236
47057 0.5407516 0.7372676 0.8518231 0.934202232 0.992962344 0.935618998
47058 0.7381735 0.7804441 0.9473044 0.292860044 0.393097617 0.737987035

In [8]:
msigdbr_collections()

   gs_collection gs_subcollection gs_collection_name
1  C1                             Positional
2  C2            CGP              Chemical and Genetic Perturbations
3  C2            CP               Canonical Pathways
4  C2            CP:BIOCARTA      BioCarta Pathways
5  C2            CP:KEGG_LEGACY   KEGG Legacy Pathways
6  C2            CP:KEGG_MEDICUS  KEGG Medicus Pathways
7  C2            CP:PID           PID Pathways
8  C2            CP:REACTOME      Reactome Pathways
9  C2            CP:WIKIPATHWAYS  WikiPathways
10 C3            MIR:MIRDB        miRDB
11 C3            MIR:MIR_LEGACY   MIR_Legacy
12 C3            TFT:GTRD         GTRD
13 C3            TFT:TFT_LEGACY   TFT_Legacy
14 C4            3CA              Curated Cancer Cell Atlas gene sets
15 C4            CGN              Cancer Gene Neighborhoods
16 C4            CM               Cancer Modules
17 C5            GO:BP            GO Biological Process
18 C5            GO:CC            GO Cellular Component
19 C5            GO:MF            GO Molecular Function
20 C5            HPO              Human Phenotype Ontology
21 C6                             Oncogenic Signature
22 C7            IMMUNESIGDB      ImmuneSigDB
23 C7            VAX              HIPC Vaccine Response
24 C8                             Cell Type Signature
25 H                              Hallmark
   num_genesets
1   302
2  3538
3    19
4   292
5   186
6   658
7   196
8  1787
9   885
10 2377
11  221
12  505
13  610
14  148
15  427
16  431
17 7583
18 1042
19 1855
20 5748
21  189
22 4872
23  347
24  866
25   50

In [58]:
gs_GO <- msigdbr(collection="C5") # , subcollection="GO:BP")
gs_GO_list <- tapply(gs_GO$gene_symbol, INDEX=gs_GO$gs_name, FUN=list)
gs_GO_list <- gs_GO_list[grep("^HP", names(gs_GO_list), invert=TRUE)]
gs_GO_list <- gs_GO_list[grep("^GOCC", names(gs_GO_list), invert=TRUE)]

In [60]:
length(gs_GO_list)

[1] 9438

In [61]:
min_set_size <- 5
max_set_size <- 200

set_sizes <- lengths(gs_GO_list)
mask <- (set_sizes < max_set_size) & (set_sizes > min_set_size)
gs_GO_list <- gs_GO_list[mask]

print(length(gs_GO_list))

[1] 7885

In [72]:
psi_corr_df_temp <- psi_corr_df %>%
    dplyr::group_by(Gene) %>%
    slice_max(abs(`CGE Class`))
fgsea_stats <- psi_corr_df_temp$`CGE Class`
names(fgsea_stats) <- psi_corr_df_temp$Gene
fgsea_stats <- sort(abs(fgsea_stats), decreasing=TRUE)
fgsea_res <- fgsea(pathways=gs_GO_list, stats=fgsea_stats, scoreType="pos")

Warning message in preparePathwaysAndStats(pathways, stats, minSize, maxSize, gseaParam, :
“There are ties in the preranked stats (0.54% of the list).
The order of those tied genes will be arbitrary, which may produce unexpected results.”
Warning message in preparePathwaysAndStats(pathways, stats, minSize, maxSize, gseaParam, :
“There are duplicate gene names, fgsea may produce unexpected results.”

In [73]:
head(fgsea_res[order(fgsea_res$padj),], 20)

   pathway
1  GOBP_CLATHRIN_DEPENDENT_ENDOCYTOSIS
2  GOBP_PRESYNAPTIC_ENDOCYTOSIS
3  GOBP_SYNAPTIC_VESICLE_RECYCLING
4  GOBP_REGULATION_OF_POSTSYNAPSE_ORGANIZATION
5  GOBP_DENDRITE_MORPHOGENESIS
6  GOBP_NEURON_PROJECTION_ORGANIZATION
7  GOBP_NEUROTRANSMITTER_SECRETION
8  GOBP_REGULATION_OF_POSTSYNAPTIC_MEMBRANE_POTENTIAL
9  GOBP_REGULATION_OF_SYNAPSE_ASSEMBLY
10 GOMF_CLATHRIN_BINDING
11 GOBP_PRESYNAPSE_ORGANIZATION
12 GOBP_DENDRITIC_SPINE_DEVELOPMENT
13 GOBP_REGULATION_OF_NEURONAL_SYNAPTIC_PLASTICITY
14 GOBP_DENDRITIC_SPINE_MORPHOGENESIS
15 GOBP_PROTEIN_LOCALIZATION_TO_CELL_JUNCTION
16 GOBP_NEURON_PROJECTION_EXTENSION
17 GOBP_HOMOPHILIC_CELL_ADHESION_VIA_PLASMA_MEMBRANE_ADHESION_MOLECULES
18 GOBP_REGULATION_OF_POSTSYNAPTIC_MEMBRANE_NEUROTRANSMITTER_RECEPTOR_LEVELS
19 GOBP_CORTICAL_CYTOSKELETON_ORGANIZATION
20 GOBP_CORTICAL_ACTIN_CYTOSKELETON_ORGANIZATION
   pval         padj         log2err   ES        NES      size
1  2.477969e-09 6.496408e-06 0.7749390 0.7038424 1.993955  42
2  1.998369e-09 6.496408e-06 0.7749390 0.6315182 1.862743  69
3  1.838503e-09 6.496408e-06 0.7881868 0.6250810 1.850358  73
4  3.823688e-09 7.518327e-06 0.7614608 0.5945489 1.788383  95
5  9.622530e-09 1.430660e-05 0.7477397 0.5664860 1.715168 103
6  1.091413e-08 1.430660e-05 0.7477397 0.6225989 1.835970  65
7  2.531078e-08 2.843847e-05 0.7337620 0.5502943 1.674876 115
8  5.139330e-08 5.052604e-05 0.7195128 0.5511393 1.674667 112
9  5.925047e-08 5.177833e-05 0.7195128 0.5612990 1.693907 100
10 7.707764e-08 6.062156e-05 0.7049757 0.6849472 1.940358  40
11 1.254091e-07 8.966752e-05 0.6901325 0.7209557 1.994431  31
12 1.823163e-07 1.128517e-04 0.6901325 0.5947590 1.754317  69
13 1.865317e-07 1.128517e-04 0.6901325 0.6520936 1.864540  45
14 3.367801e-07 1.891982e-04 0.6749629 0.6613679 1.874913  41
15 4.555183e-07 2.388434e-04 0.6749629 0.5533848 1.658352  89
16 4.895747e-07 2.406566e-04 0.6594444 0.5279763 1.610100 120
17 5.491737e-07 2.540736e-04 0.6594444 0.5589466 1.670290  84
18 7.364855e-07 3.218033e-04 0.6594444 0.5505760 1.649156  88
19 9.668723e-07 4.002343e-04 0.6435518 0.6371946 1.821939  45
20 1.137996e-06 4.326156e-04 0.6435518 0.6969706 1.939008  33
   leadingEdge
1  PICALM , SGIP1  , FCHSD2 , CLTA   , CLTC   , SCYL2  , SNAP91 , CLTB   , AP2M1  , AP2A1  , AP2B1  , MAGI2  , ITSN2  , ITSN1  , SMAP1  , TNK2   , PIP5K1C, INPP5F , ITGA4  , LMBRD1 , DNM1   , CANX   , AP2A2  , GAK
2  BIN1   , SGIP1  , CLTA   , ATP8A1 , TBC1D24, BLTP1  , DNM3   , CLTB   , AP2M1  , AP2A1  , NLGN3  , AP2B1  , ITSN2  , ITSN1  , PPP3CB , PPP3CC , SYNJ1  , PIP5K1C, ROCK1  , MYLK   , DNM2   , AMPH   , SNX9   , AP3B2  , ACTB   , CALM1  , DNM1   , SNCA   , SYT7   , RAB27B , AP3S1  , CANX   , AP2A2  , GAK    , LRRK2  , AP1G1  , CTBP1  , SCRIB  , CALM2  , SNCB   , RAC1   , CALM3  , AP3S2  , EPS15L1
3  BIN1   , GIT1   , SGIP1  , CLTA   , ATP8A1 , TBC1D24, BLTP1  , DNM3   , CLTB   , AP2M1  , AP2A1  , NLGN3  , AP2B1  , ITSN2  , GIT2   , ITSN1  , GRIPAP1, PPP3CB , PPP3CC , SYNJ1  , PIP5K1C, ROCK1  , MYLK   , DNM2   , AMPH   , SNX9   , AP3B2  , ACTB   , DNM1   , SNCA   , SYT7   , RAB27B , AP3S1  , CANX   , AP2A2  , GAK    , LRRK2  , AP1G1  , CTBP1  , SCRIB  , SNCB   , RAC1   , CALM3  , AP3S2  , EPS15L1
4  DOCK10  , SRCIN1  , APP     , PPFIA2  , RELN    , DOCK4   , PTPRD   , ABI2    , PTPRS   , NRCAM   , CAMK2B  , ELMO1   , SIPA1L1 , ITSN1   , DBN1    , NF1     , CDKL5   , PUM2    , STAU2   , CAPRIN2 , GRID2   , DVL1    , RTN4    , AKT1    , ABHD17A , CYFIP2  , KIF1A   , PAK3    , LRP8    , NEDD8   , MARK1   , SLC12A5 , ARHGAP44, CDH2    , LATS1   , NRXN2   , GPRASP3 , LRRK2   , HTR4    , ASIC2   , NAE1    , GRIN2B  , ZMYND8  , ASIC1   , PRICKLE1, CHMP2B  , NUMBL   , PLPPR4
5  DOCK10   , SRCIN1   , PPFIA2   , NSMF     , MINK1    , RELN     , PICALM   , KIDINS220, VLDLR    , PTPRD    , TBC1D24  , MEF2A    , ABI2     , PARP6    , DLG4     , ABI1     , CHRNA7   , CAMK2B   , SIPA1L1  , MAP2     , DBN1     , CDKL5    , STAU2    , CAPRIN2  , DVL1     , CTNND2   , CDKL3    , ATG16L1  , KIF1A    , PAK3     , LRP8     , PHACTR1  , CHRNB2   , RAPGEF2  , TRPC6    , ARHGAP44 , BTBD3    , CTNNA2   , NEDD4L   , PPP3CA   , GPRASP3  , LRRK2    , RERE     , TNIK     , GSK3B    , NUMBL    , ELAVL4   , HECW1    , SS18L1
6  DOCK10  , SRCIN1  , APP     , PPFIA2  , DCTN1   , RELN    , PTPRD   , ABI2    , DLG4    , CHRNA7  , KIFBP   , CAMK2B  , SIPA1L1 , DBN1    , PLS1    , STAU2   , CAPRIN2 , DVL1    , CTNND2  , CTTN    , KIF1A   , PAK3    , ITGA3   , LRP8    , MTMR2   , ARHGAP44, PICK1   , NMNAT3  , GPRASP3 , LRRK2   , GRIN2B  , ZMYND8
7  GIT1    , PPFIA2  , RAB3GAP1, CASK    , BRSK1   , KMO     , ATP2A2  , DNAJC5  , PNKD    , AP2B1   , MEF2C   , NF1     , SYNJ1   , PIP5K1C , CADPS   , DVL1    , BLOC1S6 , UNC13B  , DOC2A   , RPH3A   , SNAP23  , NAPB    , RIMS1   , PREPL   , CACNB4  , NRXN1   , NGF     , SYT5    , CADPS2  , SYT1    , STX2    , DYSF    , GRM4    , SNAP25  , NAPA    , STXBP1  , PPFIA3  , SNCA    , SYT7    , SEPTIN5 , STXBP5  , FMR1    , PPP3CA  , NRXN2   , SNAPIN  , LRRK2   , PTPRN2  , CAMK2A  , MCTP1   , ABCC8   , ASIC1   , CPLX2   , SCRIB   , TSPOAP1 , PCLO    , LIN7B   , SYNGR3  , BRAF    , MICU3   , SNCAIP  , CALM3   , SNAP47  , PDZD11  , EFR3A   , PRRT2   , PRKN
8  APP     , RELN    , TBC1D24 , RAB3GAP1, CHRNA6  , GABBR1  , DLG4    , GRIK1   , GRM1    , NLGN3   , CHRNA7  , MEF2C   , RGS7    , GRIA2   , GRIA4   , GRID2   , GRIK2   , DVL1    , GABRG2  , HTR3A   , UNC13B  , GRIN1   , AKT1    , ADORA1  , GABRB2  , ATXN1   , P2RX2   , RIMS1   , NRXN1   , GLRA3   , CHRNB2  , RGS4    , MTMR2   , GRIA3   , ABAT    , CHRNA2  , CELF4   , GABRA4  , MPP2    , GRIA1   , NPAS4   , SNCA    , SLC8A3  , SLC29A1 , NLGN4X  , P2RX4   , GLRB    , PPP3CA  , LRRK2   , GRIN2B  , ZMYND8  , GRIN2A  , GSK3B   , GLRA1   , PRKCZ   , GSK3A   , GABRB3
9  DOCK10  , APP     , DOCK4   , VLDLR   , PTPRD   , EIF4G1  , ADGRB2  , CTNNB1  , PTPRS   , IQSEC2  , NLGN3   , MEF2C   , CLSTN1  , ELMO1   , PUM2    , AGRN    , MYCBP2  , STAU2   , ST8SIA2 , GRID2   , SETD5   , RTN4    , CYFIP2  , NRXN1   , NEDD8   , CHRNB2  , ROBO2   , MARK1   , SLC12A5 , NTRK3   , SNCA    , LATS1   , NLGN4X  , NTRK1   , FLRT3   , NRXN2   , GPRASP3 , LRRN3   , HTR4    , RAB17   , ASIC2   , NAE1    , CHD4    , ASIC1   , PRICKLE1, NUMBL   , LIN7B   , ADNP
10 BIN1  , EPN1  , PICALM, TOM1L2, CLTA  , CLTC  , AFTPH , SNAP91, CLTB  , AP2B1 , EPN2  , NCALD , SMAP1 , AP1B1 , SYT5  , NSG2  , SYT1  , LMBRD1, EPN3  , TRPC6 , SYT7  , NSG1  , CEMIP , GAK   , LRRK2
11 PLS3    , APP     , PPFIA2  , CLASP2  , PTPRD   , EIF4G1  , DAAM1   , NLGN3   , CACNA2D3, CNTN5   , GRID2   , DVL1    , PCDH17  , NRXN1   , NTRK3   , SNCA    , NLGN4X  , SNAPIN  , CHD4    , CAP2    , PCLO
12 DOCK10  , SRCIN1  , GIT1    , PPFIA2  , RELN    , PTPRD   , ABI2    , PTPRS   , DLG4    , PAK4    , CAMK2B  , MEF2C   , SIPA1L1 , ITSN1   , DBN1    , SDK1    , STAU2   , CAPRIN2 , DVL1    , CTNND2  , KIF1A   , PAK3    , LRP8    , SLC12A5 , ARHGAP44, FMR1    , GPRASP3 , LRRK2   , HDAC2   , CAMK2A  , ZMYND8
13 APP     , NSMF    , CAMK2D  , NCDN    , RAB3GAP1, NPTN    , DLG4    , HRAS    , SYNGAP1 , CAMK2B  , DBN1    , NF1     , SHISA9  , GRIK2   , CAMK2G  , RASGRF1 , GRIN1   , FXR1    , SLC4A10 , FXR2    , PPFIA3  , SNCA    , FMR1    , KRAS    , CNTN2   , GRIN2B  , CAMK2A  , MCTP1   , GRIN2A  , GSG1L
14 DOCK10 , SRCIN1 , PPFIA2 , RELN   , PTPRD  , ABI2   , DLG4   , CAMK2B , SIPA1L1, DBN1   , STAU2  , CAPRIN2, DVL1   , CTNND2 , KIF1A  , PAK3   , LRP8
15 GIT1    , EPB41L3 , DLG1    , RELN    , MAPK8IP3, DLG3    , GPHN    , DLG4    , HRAS    , IQSEC2  , STX3    , CLSTN1  , GRIP1   , GRIPAP1 , MAPT    , CTNND1  , STAU2   , DVL1    , STAU1   , ERBB4   , NRXN1   , LRRC7   , FERMT2  , MAPK9   , ACTB    , FLNA    , ARHGAP44, TJP3    , NSG1    , TJP2    , RAB27B  , NRXN2   , ASIC2   , MAP2K1  , GRIN2A  , LAMTOR3 , SCRIB   , PCLO    , DLG2    , LAMTOR2 , LGI1
16 CLASP2  , SPAG9   , ZFYVE27 , CTNNB1  , PTPRS   , NRCAM   , GOLGA4  , MACF1   , NLGN3   , ITSN2   , SLIT2   , ALCAM   , MAP2    , CDKL5   , PPP3CB  , NDEL1   , MAPT    , RUFY3   , ST8SIA2 , DVL1    , CDKL3   , SMURF1  , CTTN    , ATG16L1 , SEMA4F  , RTN4    , CPNE1   , DNM2    , DDR1    , CYFIP2  , SEMA6D  , RAPH1   , SLC9A6  , RIMS1   , NGF     , TRIM46  , SYT1    , ITGA4   , NTRK3   , VEGFA   , NEDD4L  , L1CAM   , OSTN    , FLRT3   , AURKA   , SPG11   , PRICKLE1, GSK3B   , PAK6    , PRKCZ   , SEMA6C  , ADNP    , C9orf72 , FN1     , PAK1    , SIN3A   , EIF2AK4
17 CADM1  , FAT1   , PTPRM  , NPTN   , ROBO1  , CLSTN1 , CADM2  , PALLD  , SDK2   , SDK1   , PTPRR  , RET    , CDH12  , PCDH11X, CNTN4  , PTPN23 , PCDH17 , CADM3  , CDH9   , BSG    , TRO    , CNTN6  , TENM3  , ROBO2  , PKD1   , PTPRT  , CDH13  , PCDH19 , CDH2   , PCDHGC3, PTPRG  , L1CAM  , CDH18  , CDHR1  , CNTN2
18 GIT1    , EPB41L3 , DLG1    , NCDN    , DLG3    , GPHN    , DLG4    , HRAS    , IQSEC2  , AP2M1   , AP2A1   , STX3    , AP2B1   , SUSD4   , CLSTN1  , GRIP1   , GRIPAP1 , AGAP3   , PORCN   , FLOT2   , CTNND1  , GRID2   , NRG1    , ERBB4   , PPFIA1  , LRRC7   , NSG2    , ERBIN   , CPT1C   , NUMB    , SLC12A5 , SNX6    , ARHGAP44, NSG1    , AP2A2   , EPS8    , MAP2K1  , GSG1L   , SCRIB   , RDX     , DLG2    , LGI1    , HPCA    , PRKN    , RAP2A   , SHISA6  , USP6    , VAC14   , FRRS1L  , TMEM108 , CBLB    , KIF2C   , ALS2
19 EPB41L3, DLG1   , EPB41L1, FMNL2  , NCKAP1 , KIF21A , PPFIBP1, EPB41L2, PLS1   , PLEC   , ROCK1  , FHOD1  , FMNL1  , PPFIA1 , PPP2R3C, LCP1   , EPB41  , IQGAP2 , ECT2   , RACGAP1, KCNC3  , FHOD3
20 EPB41L3, DLG1   , EPB41L1, FMNL2  , NCKAP1 , EPB41L2, PLS1   , PLEC   , ROCK1  , FHOD1  , FMNL1  , LCP1   , EPB41  , IQGAP2 , ECT2   , RACGAP1, KCNC3  , FHOD3

In [66]:
library(dplyr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:data.table’:

    between, first, last


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [75]:
psi_corr_df_temp <- psi_corr_df %>%
    dplyr::group_by(Gene) %>%
    slice_max(abs(`Deep layer glutamatergic`))
fgsea_stats <- psi_corr_df_temp$`Deep layer glutamatergic`
names(fgsea_stats) <- psi_corr_df_temp$Gene
fgsea_stats <- sort(abs(fgsea_stats), decreasing=TRUE)
fgsea_res <- fgsea(pathways=gs_GO_list, stats=fgsea_stats, scoreType="pos")

Warning message in preparePathwaysAndStats(pathways, stats, minSize, maxSize, gseaParam, :
“There are ties in the preranked stats (0.48% of the list).
The order of those tied genes will be arbitrary, which may produce unexpected results.”
Warning message in preparePathwaysAndStats(pathways, stats, minSize, maxSize, gseaParam, :
“There are duplicate gene names, fgsea may produce unexpected results.”

In [76]:
head(fgsea_res[order(fgsea_res$padj),], 20)

   pathway                                                       pval
1  GOBP_NEUROTRANSMITTER_SECRETION                               8.725087e-11
2  GOBP_SYNAPTIC_VESICLE_RECYCLING                               2.190209e-09
3  GOBP_SYNAPTIC_VESICLE_EXOCYTOSIS                              3.823688e-09
4  GOBP_ACTIN_FILAMENT_BUNDLE_ORGANIZATION                       5.815823e-09
5  GOBP_NEURON_MIGRATION                                         9.235051e-09
6  GOBP_NEURON_PROJECTION_EXTENSION                              1.104329e-08
7  GOBP_PRESYNAPTIC_ENDOCYTOSIS                                  9.880849e-09
8  GOBP_CLATHRIN_DEPENDENT_ENDOCYTOSIS                           1.518659e-08
9  GOBP_POSITIVE_REGULATION_OF_SUPRAMOLECULAR_FIBER_ORGANIZATION 3.156667e-08
10 GOBP_POSITIVE_REGULATION_OF_CYTOSKELETON_ORGANIZATION         1.043428e-07
11 GOBP_CALCIUM_ION_TRANSMEMBRANE_IMPORT_INTO_CYTOSOL            1.211938e-07
12 GOBP_RESPONSE_TO_CALCIUM_ION                                  1.570242e-07
13 GOBP_DENDRITE_MORPHOGENESIS                                   1.928547e-07
14 GOBP_CARDIAC_CONDUCTION                                       3.367801e-07
15 GOBP_CELL_SUBSTRATE_JUNCTION_ORGANIZATION                     3.113630e-07
16 GOBP_STRESS_FIBER_ASSEMBLY                                    3.494886e-07
17 GOMF_CALCIUM_ION_TRANSMEMBRANE_TRANSPORTER_ACTIVITY           3.833780e-07
18 GOBP_CYTOKINESIS                                              5.491737e-07
19 GOBP_POSITIVE_REGULATION_OF_SYNAPTIC_TRANSMISSION             6.258012e-07
20 GOBP_EXOCYTIC_PROCESS                                         1.086659e-06
   padj         log2err   ES        NES      size
1  6.862281e-07 0.8390889 0.5711961 1.796926 115
2  8.612996e-06 0.7749390 0.6033552 1.838028  73
3  1.002444e-05 0.7614608 0.6072599 1.854188  76
4  1.143536e-05 0.7614608 0.5417796 1.711748 123
5  1.240792e-05 0.7477397 0.5334522 1.687344 125
6  1.240792e-05 0.7477397 0.5378535 1.695987 120
7  1.240792e-05 0.7477397 0.6104444 1.849815  69
8  1.493031e-05 0.7337620 0.6861601 1.999289  42
9  2.758576e-05 0.7195128 0.5308140 1.677102 123
10 8.206564e-05 0.7049757 0.5092648 1.618580 133
11 8.665356e-05 0.6901325 0.5169331 1.635093 125
12 1.029163e-04 0.6901325 0.5429928 1.686524  97
13 1.166771e-04 0.6901325 0.5358365 1.672842 103
14 1.717955e-04 0.6749629 0.5682400 1.723285  70
15 1.717955e-04 0.6749629 0.5674120 1.734596  77
16 1.717955e-04 0.6749629 0.5626470 1.727999  82
17 1.773687e-04 0.6749629 0.5024767 1.593659 130
18 2.399584e-04 0.6594444 0.5007715 1.594359 139
19 2.590488e-04 0.6594444 0.5168181 1.624425 114
20 4.197976e-04 0.6435518 0.5888311 1.773884  65
   leadingEdge
1  NRXN2   , CADPS2  , PPP3CA  , UNC13B  , CADPS   , NRXN1   , MEF2C   , PPFIA3  , RIMS1   , TSPOAP1 , RAB3GAP1, AP2B1   , SNAP23  , PNKD    , CASK    , CAMK2A  , SCRIB   , ATP2A2  , SYNJ1   , DNAJC5  , NF1     , PDZD11  , SYT5    , GIT1    , UNC13A  , CACNB4  , RAP1A   , GGCX    , STXBP1  , PIP5K1C , STX2    , DVL1    , CALM3   , PCLO    , DYSF    , SV2B    , PPFIA2  , SYT7    , SYN1    , STXBP5  , SNAP25  , STX1A   , SYT1    , LRRK2   , PSEN1   , RPH3A   , RIMS2   , GRM4    , BLOC1S6 , MICU3   , ASIC1
2  DNM2   , AP2A1  , SGIP1  , CLTB   , ITSN1  , CLTA   , AP2M1  , TBC1D24, DNM3   , AP2B1  , BLTP1  , DNM1   , GIT2   , SCRIB  , GAK    , SYNJ1  , ROCK1  , GIT1   , NLGN3  , ITSN2  , PPP3CC , PIP5K1C, AP1G1  , PPP3CB , AMPH   , BIN1   , CALM3  , SYT7   , SNX9   , MYLK   , STX1A  , LRRK2
3  CADPS2  , PPP3CA  , UNC13B  , CADPS   , PPFIA3  , RIMS1   , RAB3GAP1, SNAP23  , CASK    , SCRIB   , ATP2A2  , SYNJ1   , DNAJC5  , SYT5    , GIT1    , UNC13A  , CACNB4  , RAP1A   , STXBP1  , PIP5K1C , STX2    , DVL1    , CALM3   , PCLO    , SV2B    , PPFIA2  , SYT7    , SYN1    , STXBP5  , SNAP25  , STX1A   , SYT1    , LRRK2   , PSEN1   , RPH3A   , RIMS2
4  ADD1     , DNM2     , CALD1    , FMN2     , DMTN     , CLASP2   , SORBS1   , PPFIA1   , CLASP1   , ARHGEF10L, FERMT2   , CARMIL1  , ZYX      , CD47     , SRC      , EPHA1    , ARRB1    , TPM1     , ACTN1    , PHLDB2   , FLNA     , NF2      , LIMA1    , ROCK1    , SPIRE1   , MET      , LIMCH1   , RHOA     , MYO1B    , PLS3     , MTSS1    , PDCD10   , TTC8     , PXN      , PHACTR1  , EVL      , CCDC88A  , INPP5K   , HSP90B1  , ARAP1    , BBS4     , BLOC1S6  , ALMS1    , TSC1     , PAK1     , ZEB2     , RHOC
5  NRCAM  , GPM6A  , CAMK2B , ADGRL3 , ABI2   , MEF2C  , MYH10  , SEMA6A , CHL1   , SEPTIN4, YWHAE  , TBC1D24, ABI1   , NSMF   , FLNA   , CAMK2A , NTNG1  , POMGNT2, NDEL1  , SOCS7  , CTNNA2 , UNC5C  , MARK1  , NEO1   , RHOA   , PEX5   , CTNNB1 , PCM1   , ITGA3  , TUBA1A , RNF7   , APBB2  , GFRA3  , WDR62  , PHACTR1, ADAM17 , CNTN2  , SPOCK1 , PSEN1  , LHX6   , VRK1   , LARGE1 , NR4A2  , DRD2   , UNC5D  , DCC    , NDE1   , BBS4   , ASPM   , NAV1
6  MACF1   , NRCAM   , DNM2    , IQGAP1  , CLASP2  , PTPRS   , CYFIP2  , RIMS1   , GOLGA4  , ZFYVE27 , MAPT    , CTTN    , POSTN   , HDAC6   , RTN4    , SPAG9   , MAG     , MAP2    , NDEL1   , DCLK1   , CDKL3   , NLGN3   , SEMA6D  , ITSN2   , UNC13A  , ATG16L1 , PPP3CB  , CTNNB1  , SLC9A6  , SMURF1  , DVL1    , ARHGAP4 , CDH1    , DDR1    , SEMA6C  , ALCAM   , SYT1    , PRICKLE1, RIMS2   , C9orf72 , PRKCZ   , SEMA4F  , SEMA5B  , BCL11A  , GSK3B   , DIP2B   , RNF157  , RAPH1   , PAK1    , CPNE9   , ADNP    , SPAG6   , RUFY3   , MT3     , SLIT2   , ST8SIA2 , CPNE1   , ITGB1   , L1CAM   , OSTN    , SIN3A   , FLRT3   , CPNE6   , NTRK3   , VEGFA   , PLAA    , PAFAH1B1, MEGF8   , AURKA
7  DNM2   , AP2A1  , SGIP1  , CLTB   , ITSN1  , CLTA   , AP2M1  , TBC1D24, DNM3   , AP2B1  , BLTP1  , DNM1   , CALM2  , SCRIB  , GAK    , SYNJ1  , ROCK1  , NLGN3  , ITSN2  , PPP3CC , PIP5K1C, AP1G1  , PPP3CB , AMPH   , BIN1   , CALM3  , SYT7   , SNX9   , MYLK   , STX1A  , LRRK2  , CANX   , AP3S1  , NECAP1 , SNCA   , RAB27B , PIK3C3 , AP3B2  , ATP8A1 , AP3M2
8  PICALM , AP2A1  , SGIP1  , CLTB   , ITSN1  , SNAP91 , CLTA   , CLTC   , AP2M1  , AP2B1  , DNM1   , SCYL2  , SMAP1  , GAK    , ITSN2  , PIP5K1C, FCHSD2 , FCHO1  , TNK2   , MAGI2  , INPP5F , SLC9B2 , CANX   , PIK3CB
9  GSN      , PDE4DIP  , APP      , CLIP1    , ABI2     , CLASP1   , ARHGEF10L, FERMT2   , CARMIL1  , NUMA1    , NCKAP1   , CD47     , EPHA1    , MAPT     , DLG1     , CTTN     , TPM1     , FLNA     , NF2      , CKAP5    , GIT1     , MET      , CDK5RAP2 , DCTN1    , LIMCH1   , RHOA     , NPHS1    , FCHSD2   , BIN1     , PRKD1    , MTSS1    , NAV3     , PXN      , SNX9     , EVL      , CCDC88A  , STMN2    , PSEN1    , TENM1    , SKA1     , ACTN2    , ARL2     , PRKCE
10 GSN      , PDE4DIP  , CLIP1    , ABI2     , CLASP1   , ARHGEF10L, FERMT2   , CARMIL1  , NUMA1    , NCKAP1   , CD47     , EPHA1    , MAPT     , DLG1     , CTTN     , TPM1     , FLNA     , NF2      , POC1B    , CKAP5    , GIT1     , MET      , CDK5RAP2 , ADD3     , DCTN1    , LIMCH1   , RHOA     , NPHS1    , FCHSD2   , NUP62    , BIN1     , PRKD1    , MTSS1    , NAV3     , PXN      , SNX9     , EVL      , CCDC88A  , STMN2    , TENM1    , SKA1     , ACTN2    , ARL2     , PRKCE
11 ANK2     , PPP3CA   , ATP2B4   , ADCYAP1R1, PKD2     , GRIN1    , CAMK2D   , BAK1     , ASPH     , RYR1     , PLCH1    , CALM2    , RYR3     , FLNA     , DMD      , PLCB4    , PPP3CC   , CAPN3    , NPSR1    , CACNA1G  , PPP3CB   , PRKD1    , PLCB2    , P2RX4    , CACNA1A  , CALM3    , CACNA1D  , SLC8A3   , RYR2     , HTR2A    , P2RX5    , DIAPH1   , P2RY6    , DHRS7C   , SLC24A2  , CACNA1S  , SLC8A1   , PLCE1    , CACNA1C  , PRKCE    , DRD2     , CEMIP    , CACNA1E  , CLIC2    , ITPR1
12 ADD1    , PPP3CA  , IQGAP1  , ANXA7   , KCNMA1  , APP     , NRXN1   , MEF2C   , PKD2    , CAMK2D  , KCNIP2  , ASPH    , RYR1    , ABCC9   , MICU1   , CALM2   , RYR3    , MEF2A   , STIM1   , SEC31A  , GIPR    , KCNH1   , CAPN3   , CPNE4   , RASGRP2 , CALM3   , ECT2    , CPNE7   , RYR2    , P2RX5   , D2HGDH  , TUBA1A  , SYT1    , HPCA    , SLC25A23, HNRNPD  , MICU3   , CARF    , CPNE9   , ADAM9   , ANXA11  , NCSTN   , TNNT2   , MICU2   , ADGRV1  , CPNE1
13 PICALM   , PPP3CA   , CAMK2B   , ABI2     , DBN1     , MINK1    , TBC1D24  , CAPRIN2  , KIF1A    , SIPA1L1  , ABI1     , NSMF     , HDAC6    , MEF2A    , PARP6    , MAP2     , CTNNA2   , PTPRD    , CDKL3    , KIDINS220, HECW2    , TNIK     , ATG16L1  , DOCK10   , SEMA4D   , SULT4A1  , ELAVL4   , PAK3     , DVL1     , ARHGAP44 , DLG4     , TRAK1    , PPFIA2   , HECW1    , CHRNB2   , PHACTR1
14 ANK2   , ATP2B4 , ATP2B1 , CAMK2D , YWHAE  , SRC    , KCNN2  , ABCC9  , CALM2  , MEF2A  , FLNA   , TRPM4  , ATP2A2 , KCND3  , SCN3B  , CACNA1G, ATP2B2 , BIN1   , CORIN  , CALM3  , CACNA1D, SLC8A3 , RYR2   , IRX3   , CTNNA3 , SLC8A1 , CACNA1C
15 DST     , MACF1   , MAP4K4  , ARHGEF7 , DMTN    , CLASP2  , SORBS1  , COL16A1 , PLEC    , CLASP1  , FERMT2  , PTPRK   , SRC     , PTK2    , CTTN    , ACTN1   , PHLDB2  , TNS1    , GPM6B   , ROCK1   , LIMCH1  , RHOA    , LIMS1   , ITGA6   , ITGA2   , ACTN2   , PRICKLE1, PTPRA   , TSC1    , IQSEC1  , DUSP3
16 DNM2     , CLASP2   , SORBS1   , PPFIA1   , CLASP1   , ARHGEF10L, FERMT2   , CARMIL1  , ZYX      , CD47     , SRC      , EPHA1    , ARRB1    , TPM1     , PHLDB2   , NF2      , ROCK1    , MET      , LIMCH1   , RHOA     , PDCD10   , TTC8     , PXN      , PHACTR1  , EVL      , CCDC88A  , INPP5K   , ARAP1    , BBS4     , ALMS1    , TSC1     , PAK1     , ZEB2     , RHOC
17 NRXN2   , GPM6A   , CACNB1  , ATP2B4  , ATP2B1  , NRXN1   , PKD2    , GRIN1   , TSPOAP1 , YWHAE   , RYR1    , MICU1   , CALM2   , RYR3    , STIM1   , TRPM4   , STIM2   , ATP2A2  , CACNA2D3, CACNA2D2, PKD1L2  , CACNB4  , GRIA3   , CACNA1G , ATP2B2  , P2RX4   , CACNA1A , CALM3   , CACNA1D , SLC8A3  , RYR2    , CACNA2D4, PKD1    , ATP2C1  , TMEM165 , TRPC4   , ATP2C2  , GRIK1   , SLC24A2 , STX1A   , CACNA1S , SLC8A1  , CACNA1C , PSEN1   , TRPM8   , REM2    , CACNA1E , MICU3   , ITPR1   , CACNG6  , CHRNA7  , ATP2B3  , CACNA1I , GRIK2   , ATP2A1  , MICU2   , TMCO1
18 EXOC7    , IQGAP1   , FMN2     , SH3GLB1  , EXOC1    , PLEC     , MYH10    , ACTR2    , MYH14    , RAB11FIP3, SEPTIN4  , PRPF40A  , CALM2    , MTMR3    , SEPTIN2  , CSPP1    , CENPV    , ROCK1    , SPIRE1   , GIT1     , ANK3     , WNK1     , MYH9     , PKP4     , TRIM36   , EXOC6B   , RHOA     , NUP62    , PKN2     , SEPTIN11 , SEPTIN6  , MYO19    , CALM3    , INCENP   , ECT2     , CDC14B   , AHCTF1   , SNX9     , KIF23    , SPART    , TTC19    , DCTN3    , PRKCE    , DRD2     , STAMBP   , BBS4     , CDC25B   , EXOC3    , APC      , EFHC1    , IST1     , ANXA11   , RHOC     , ANLN     , CHMP1A   , BIRC5    , CCP110   , ENTR1    , UVRAG    , PIK3C3
19 CAMK2G  , CLSTN1  , PPP3CA  , CAMK2B  , FXR1    , APP     , NRXN1   , ADORA1  , GRIN1   , CAMK2D  , STAU1   , RAB3GAP1, CALM2   , HDAC6   , CAMK2A  , NF1     , NLGN3   , LAMA2   , STX3    , NMU     , STXBP1  , IQSEC2  , GRIA3   , NALCN   , LGI1    , DLG4    , CALM3   , SLC8A3  , ARRB2   , SNAP25  , SLC24A2 , STX1A   , SYT1    , LARGE1  , MPP2    , PRKCE   , DRD2    , PRKCZ   , SQSTM1  , CRHR2   , MICU3   , GSK3B   , SNCA    , NCSTN   , FLOT1   , CHRNA7  , GRIK2   , SLC1A3  , BAIAP3  , PRKCG   , CYP46A1 , NTRK1   , NPTN    , NSG1    , SHANK2
20 CADPS2 , EXOC7  , UNC13B , EXOC1  , PPFIA3 , RIMS1  , SNAP23 , SCRIB  , SYNJ1  , SYT5   , RABEPK , UNC13A , STXBP1 , EXOC6B , STX2   , SYT7   , SYTL2  , STXBP5 , SNAP25 , STX1A  , SYT1   , PSEN1  , RPH3A  , RIMS2  , BLOC1S6, EXOC3  , CFTR   , SNX6   , SNCA   , ERC2   , GNAO1

In [81]:
psi_corr_df_temp <- psi_corr_df %>%
    dplyr::group_by(Gene) %>%
    slice_max(abs(`Oligo`), with_ties=FALSE)
fgsea_stats <- psi_corr_df_temp$`Oligo`
names(fgsea_stats) <- psi_corr_df_temp$Gene
fgsea_stats <- sort(abs(fgsea_stats), decreasing=TRUE)
fgsea_res <- fgsea(pathways=gs_GO_list, stats=fgsea_stats, scoreType="pos")

Warning message in preparePathwaysAndStats(pathways, stats, minSize, maxSize, gseaParam, :
“There are ties in the preranked stats (0.49% of the list).
The order of those tied genes will be arbitrary, which may produce unexpected results.”

In [82]:
head(fgsea_res[order(fgsea_res$padj),], 20)

   pathway
1  GOBP_REGULATION_OF_MRNA_PROCESSING
2  GOBP_DENDRITE_MORPHOGENESIS
3  GOBP_NEURON_PROJECTION_ORGANIZATION
4  GOBP_POSITIVE_REGULATION_OF_SUPRAMOLECULAR_FIBER_ORGANIZATION
5  GOBP_REGULATION_OF_MRNA_SPLICING_VIA_SPLICEOSOME
6  GOBP_ENSHEATHMENT_OF_NEURONS
7  GOBP_REGULATION_OF_RNA_SPLICING
8  GOBP_ACTIN_FILAMENT_BUNDLE_ORGANIZATION
9  GOBP_PRESYNAPTIC_ENDOCYTOSIS
10 GOBP_MICROTUBULE_POLYMERIZATION
11 GOBP_POSITIVE_REGULATION_OF_CYTOSKELETON_ORGANIZATION
12 GOBP_REGULATION_OF_POSTSYNAPTIC_MEMBRANE_NEUROTRANSMITTER_RECEPTOR_LEVELS
13 GOBP_SYNAPTIC_VESICLE_RECYCLING
14 GOBP_DENDRITIC_SPINE_DEVELOPMENT
15 GOBP_MICROTUBULE_POLYMERIZATION_OR_DEPOLYMERIZATION
16 GOBP_DENDRITIC_SPINE_MORPHOGENESIS
17 GOBP_ENDOTHELIAL_CELL_DEVELOPMENT
18 GOBP_REGULATION_OF_DENDRITIC_SPINE_MORPHOGENESIS
19 GOMF_SH3_DOMAIN_BINDING
20 GOMF_STRUCTURAL_CONSTITUENT_OF_SYNAPSE
   pval         padj         log2err   ES        NES      size
1  7.321436e-10 5.758310e-06 0.8012156 0.5584732 1.796588 106
2  8.546692e-08 1.459863e-04 0.7049757 0.5319861 1.710116 103
3  5.925047e-08 1.459863e-04 0.7195128 0.5884891 1.824201  65
4  5.820182e-08 1.459863e-04 0.7195128 0.5139543 1.664732 123
5  9.280755e-08 1.459863e-04 0.7049757 0.5527063 1.754187  88
6  1.211938e-07 1.588649e-04 0.6901325 0.5211866 1.680138 114
7  1.844240e-07 2.072135e-04 0.6901325 0.5002802 1.631530 137
8  2.732376e-07 2.387793e-04 0.6749629 0.5013787 1.623999 123
9  2.562930e-07 2.387793e-04 0.6749629 0.5745022 1.789284  69
10 3.664333e-07 2.710864e-04 0.6749629 0.5521873 1.741604  80
11 3.791418e-07 2.710864e-04 0.6749629 0.4911670 1.598174 133
12 4.470042e-07 2.858906e-04 0.6749629 0.5384493 1.708938  88
13 4.725465e-07 2.858906e-04 0.6749629 0.5635887 1.763156  73
14 9.668723e-07 5.431751e-04 0.6435518 0.5621068 1.750678  69
15 1.446020e-06 7.581964e-04 0.6435518 0.5072099 1.634286 110
16 2.287231e-06 1.029449e-03 0.6272567 0.6282504 1.870294  41
17 2.149656e-06 1.029449e-03 0.6272567 0.5958180 1.805651  49
18 2.356019e-06 1.029449e-03 0.6272567 0.6866237 1.976797  29
19 3.353442e-06 1.318741e-03 0.6272567 0.5110439 1.625717  90
20 3.215867e-06 1.318741e-03 0.6272567 0.7692510 2.067459  17
   leadingEdge
1  SRRM1  , TRA2B  , SNRNP70, TRA2A  , PCBP4  , DHX9   , UPF3A  , QKI    , MAGOHB , SRSF3  , SRSF7  , RBM25  , SRSF6  , RBM5   , SRPK2  , ARGLU1 , CELF6  , RBM39  , CDK11B , SF1    , SLTM   , ACIN1  , RNPS1  , DHX36  , RBFOX2 , REST   , NSRP1  , PTBP1  , SRPK1  , CELF4  , DDX17  , CIRBP  , FMR1   , RBM4   , SAFB   , SAFB2  , HNRNPL , DAZAP1 , RBM23  , NPM1   , RBM10  , HNRNPA1, THRAP3 , SON    , MAGOH  , HDAC7  , SRSF10 , HNRNPU , THUMPD2, PUF60  , CELF2  , U2AF2  , UPF1   , NUP98  , PRPF19 , DDX5   , RBPMS  , IWS1   , BARD1  , CPEB1  , TIA1   , RBM42
2  SRCIN1   , DOCK10   , PPFIA2   , VLDLR    , RELN     , MINK1    , PTPRD    , PARP6    , KIDINS220, BTBD3    , SEMA4D   , LRP8     , PICALM   , DLG4     , NSMF     , KIF1A    , PHACTR1  , ABI2     , TBC1D24  , SHANK3   , MAP2     , MEF2A    , RAPGEF2  , ABI1     , CHRNA7   , STAU2    , CAPRIN2  , DHX36    , NEDD4    , KLF7     , ATP7A    , GPRASP3  , DBN1     , SIPA1L1  , CTNND2   , CAMK2B   , TRAK1    , SLC11A2  , SS18L1   , TANC2    , KNDC1    , CDKL3    , ITGB1    , PTEN     , YWHAH    , ATG16L1  , NEDD4L   , DTNBP1   , SULT4A1  , NRP1     , ARHGAP33 , ARHGAP44 , HDAC6
3  SRCIN1  , DOCK10  , PPFIA2  , RELN    , APP     , DCTN1   , PTPRD   , LRP8    , DLG4    , KIF1A   , ABI2    , SHANK3  , PSEN1   , CHRNA7  , STAU2   , CAPRIN2 , DHX36   , KIFBP   , GPRASP3 , DBN1    , SIPA1L1 , NMNAT3  , CTNND2  , ITGA3   , CAMK2B  , LGMN    , MTMR2   , PICK1   , GRIN2B  , ARF1    , TANC2   , INSR    , PLS1    , CTTN    , PTEN    , DTNBP1  , ARHGAP33, ARHGAP44, HDAC6   , GSK3B
4  BIN1     , SLAIN1   , APP      , DCTN1    , DLG1     , ACTN2    , GSN      , GIT1     , LIMCH1   , MTSS1    , FERMT2   , CDK5RAP2 , CLASP1   , FCHSD2   , CD47     , FHOD1    , NF2      , NCKAP1   , ABI2     , CLIP1    , TPM1     , RAPGEF3  , SPAST    , MAPT     , PSEN1    , ARHGEF10L, CFL2     , RHOC     , CSF3     , EVL      , TESK1    , CDC42EP1 , RPS3     , TOGARAM1 , ARHGEF10 , USP8     , AKAP9    , TGFB3    , PXN      , FES      , LPAR1    , TNXB     , BRAF     , PDE4DIP  , TRPV4    , NUMA1    , ARHGEF15 , COLGALT1 , CTTN     , MLST8    , TRIM27   , FCHSD1   , CCDC88A  , NRP1     , MET      , WASF1    , ARPC2    , ARHGEF5  , PTK2B    , FLNA     , EFEMP2   , CARMIL2  , OCLN     , PAK1     , SORBS3   , CDC42
5  SRRM1  , TRA2B  , SNRNP70, TRA2A  , PCBP4  , UPF3A  , QKI    , SRSF3  , SRSF7  , RBM25  , SRSF6  , RBM5   , SRPK2  , ARGLU1 , CELF6  , RBM39  , SF1    , ACIN1  , RNPS1  , RBFOX2 , REST   , NSRP1  , PTBP1  , SRPK1  , CELF4  , DDX17  , CIRBP  , FMR1   , RBM4   , HNRNPL , DAZAP1 , RBM23  , NPM1   , RBM10  , HNRNPA1, THRAP3 , SON    , MAGOH  , SRSF10 , HNRNPU , THUMPD2, PUF60  , CELF2  , U2AF2  , UPF1   , NUP98  , PRPF19 , DDX5   , RBPMS  , TIA1   , RBM42
6  ABCA2   , NFASC   , EPB41L3 , ANK2    , SH3TC2  , SIRT2   , DLG1    , MAG     , MBP     , NRDC    , CNTN2   , HRAS    , QKI     , ERBB3   , CTNNB1  , NF1     , KLK6    , HEXA    , ACER3   , BCAS1   , TSC1    , AKT1    , LPIN1   , PLEC    , SBF2    , TMEM98  , MYRF    , NCSTN   , UGT8    , MAL     , ILK     , SLC25A46, SOX10   , ARHGEF10, DICER1  , IGF1    , NDRG1   , MTMR2   , EIF2B5  , RNF10   , JAM2    , AKT2    , LPAR1   , ACSBG1  , ERBB2   , PLP1    , POMGNT1 , SCN8A   , ERCC2   , PMP22   , DAG1    , NAB1    , CDK18   , PTEN    , PPARD   , FIG4    , MAP2K1
7  PTBP2  , SRRM1  , HNRNPH3, MBNL2  , TRA2B  , SNRNP70, TRA2A  , PCBP4  , UPF3A  , TMBIM6 , QKI    , SRSF3  , SRSF7  , RBM25  , SRSF6  , RBM5   , CCNL1  , HNRNPH1, ZNF638 , SRPK2  , ARGLU1 , CELF6  , RBM39  , CDK11B , SF1    , ACIN1  , RNPS1  , RBFOX2 , REST   , AKAP17A, NSRP1  , PTBP1  , SRPK1  , FASTK  , CELF4  , ATXN7  , DDX17  , CIRBP  , FMR1   , RBM4   , HNRNPL , DAZAP1 , RBM23  , NPM1   , RBM10  , HNRNPA1, FUS    , THRAP3 , SON    , MAGOH  , SRSF10 , HNRNPU , THUMPD2, PUF60  , CLK3   , CELF2  , U2AF2  , UPF1   , NUP98  , PRPF19 , DDX5   , RBPMS  , HNRNPLL, TIA1   , RBM42  , SETX   , CLK4   , METTL4 , MBNL1  , GRSF1  , CLK2   , ESRP1  , CCNL2  , TAF9   , PRX    , YTHDC1 , LARP7  , MBNL3  , RBM3   , ZPR1   , AHNAK  , HNRNPK , CELF1  , RBM47  , RBM38  , KHDRBS1, EXOSC10, KHDRBS3, PRMT5
8  PLS3     , ADD1     , CLASP2   , LIMCH1   , MTSS1    , FERMT2   , CLASP1   , ZEB2     , CD47     , FHOD1    , ACTN1    , NF2      , PHACTR1  , TPM1     , RAPGEF3  , SHANK3   , SORBS1   , DNM2     , TSC1     , ARHGEF10L, KCTD13   , BLOC1S6  , RDX      , FMN2     , RHOC     , SPIRE1   , USH1C    , ACTG1    , ARHGAP6  , PIK3R2   , EPS8     , EVL      , TESK1    , MYO1B    , HSP90B1  , SRC      , TJP1     , ARHGEF10 , DMTN     , LIMA1    , ARAP1    , TGFB3    , PXN      , LPAR1    , ZYX      , AIF1L    , BRAF     , F11R     , ARHGEF15 , SHROOM1  , PLS1     , ITGB1    , PPFIA1   , ROCK1    , FAM107A  , CCDC88A  , NRP1     , MET      , CORO1B   , ARHGEF5  , BBS4     , FLNA     , ARRB1    , ASAP3    , PAK1     , SORBS3   , CDC42
9  BIN1   , CLTA   , ATP8A1 , CLTB   , SGIP1  , ITSN2  , PPP3CB , AP3B2  , AP2M1  , ACTB   , NLGN3  , TBC1D24, AP2A1  , AP2A2  , AP2B1  , CALM1  , BLTP1  , DNM2   , PPP3CC , CANX   , DNM3   , ITSN1  , AMPH   , NECAP1 , ACTG1  , SYNJ1  , AP1G1  , PIP5K1C, SCRIB  , SYT7   , MX1    , PIK3C3 , DNAJC6
10 SLAIN1  , DCTN1   , GIT1    , CLASP2  , ARHGEF7 , CDK5RAP2, CLASP1  , KIF21A  , CAMSAP2 , MAP4    , CAMSAP1 , CLIP1   , MAP2    , CSNK1D  , NDEL1   , MAPT    , TUBA1A  , EML2    , NDE1    , NIN     , TUBB4A  , GOLGA2  , TBCD    , GBA2    , NME7    , RPS3    , TUBGCP3 , CCDC57  , TOGARAM1, AKAP9   , HAUS7   , FES     , CEP192  , ZNF207  , PDE4DIP , TRPV4   , NUMA1   , PCNT    , SLC39A12, TUBGCP2 , CCDC66
11 BIN1     , SLAIN1   , DCTN1    , DLG1     , ACTN2    , GSN      , GIT1     , LIMCH1   , MTSS1    , FERMT2   , CDK5RAP2 , CLASP1   , FCHSD2   , CD47     , FHOD1    , NF2      , NCKAP1   , ABI2     , CLIP1    , TPM1     , RAPGEF3  , SPAST    , MAPT     , SPAG5    , ARHGEF10L, CFL2     , RHOC     , NUP62    , CSF3     , EVL      , POC1B    , TESK1    , CDC42EP1 , RPS3     , P2RX7    , TOGARAM1 , ARHGEF10 , AKAP9    , ADD3     , TGFB3    , PXN      , FES      , LPAR1    , DYNC1H1  , BRAF     , PDE4DIP  , TRPV4    , NUMA1    , ARHGEF15 , CTTN     , GPSM2    , MLST8    , TRIM27   , FCHSD1   , CCDC88A  , NRP1     , MET      , WASF1    , ARPC2    , ARHGEF5  , PTK2B    , FLNA     , CEP295   , CARMIL2  , OCLN     , PAK1     , SORBS3   , CDC42
12 EPB41L3, DLG1   , GIT1   , SNX6   , NUMB   , DLG4   , AGAP3  , HRAS   , LRRC7  , NCDN   , AP2M1  , STX3   , EPS15  , CLSTN1 , AP2A1  , AP2A2  , AP2B1  , DLG3   , GPHN   , GRIPAP1, RDX    , PORCN  , IQSEC2 , STX4   , CBLB   , EPS8   , GRIP1  , ADAM10 , FLOT2  , SCRIB  , CTNND1 , LPAR1  , ERBIN  , ERBB2  , ATAD1  , CPT1C  , DLG2   , SUSD4  , SACM1L , GPSM2  , DAG1   , PPFIA1 , MDM2   , CNIH3  , MAP2K1 , ERBB4
13 BIN1   , CLTA   , GIT1   , ATP8A1 , CLTB   , SGIP1  , ITSN2  , PPP3CB , AP3B2  , AP2M1  , ACTB   , NLGN3  , TBC1D24, AP2A1  , AP2A2  , AP2B1  , GRIPAP1, BLTP1  , DNM2   , PPP3CC , CANX   , DNM3   , ITSN1  , GIT2   , AMPH   , ACTG1  , SYNJ1  , AP1G1  , PIP5K1C, SCRIB  , SYT7   , MX1    , PIK3C3 , DNAJC6
14 SRCIN1  , DOCK10  , PPFIA2  , RELN    , GIT1    , PTPRD   , LRP8    , DLG4    , KIF1A   , MEF2C   , ABI2    , PTPRS   , SHANK3  , PSEN1   , PAK4    , ITSN1   , STAU2   , CAPRIN2 , DHX36   , GPRASP3 , DBN1    , SIPA1L1 , FMR1    , CTNND2  , CAMK2B  , DISC1   , CAMK2A  , LPAR1   , TANC2   , C21orf91, SDK1    , PTEN    , DTNBP1  , CAMK1   , ARHGAP33, ARHGAP44, HDAC6
15 SLAIN1  , DCTN1   , GIT1    , CLASP2  , ARHGEF7 , CDK5RAP2, CLASP1  , KIF2A   , KIF21A  , CAMSAP2 , MAP4    , ARHGEF2 , CAMSAP1 , CLIP1   , SPAST   , MAP2    , STMN4   , CSNK1D  , NDEL1   , MAPT    , TUBA1A  , EML2    , NDE1    , NIN     , TUBB4A  , GOLGA2  , TBCD    , ATXN7   , GBA2    , NME7    , RPS3    , TUBGCP3 , CCDC57  , TOGARAM1, AKAP9   , HAUS7   , FES     , CEP192  , ZNF207  , PDE4DIP , TRPV4   , NUMA1   , APC     , PCNT    , SLC39A12, TUBGCP2 , CCDC66
16 SRCIN1 , DOCK10 , PPFIA2 , RELN   , PTPRD  , LRP8   , DLG4   , KIF1A  , ABI2   , SHANK3 , STAU2  , CAPRIN2, DHX36  , GPRASP3, DBN1   , SIPA1L1, CTNND2 , CAMK2B
17 ADD1    , MAGI1   , AFDN    , PTPRS   , RAPGEF3 , RAPGEF1 , RAPGEF2 , IKBKB   , RDX     , CCM2    , RAPGEF6 , TJP2    , VEGFA   , TJP1    , AMOTL2  , RAB1B   , MYD88   , PLOD3   , F11R    , RAP1B   , PPP1R12A, CLIC4   , ROCK1   , TJP3    , HPSE    , VCL     , MET     , TNFRSF1A, RAP1A   , PDE2A
18 SRCIN1 , PPFIA2 , RELN   , PTPRD  , LRP8   , KIF1A  , ABI2   , SHANK3 , STAU2  , CAPRIN2, DHX36  , GPRASP3, DBN1   , SIPA1L1, CAMK2B
19 LRP2    , CIT     , ADAM15  , DOCK4   , SGIP1   , QKI     , ABI2    , RAPGEF1 , SHANK3  , EPS15   , SYNGAP1 , MAPT    , ARHGAP17, DNM2    , ABI1    , RUFY1   , ELMO1   , SOCS7   , ENAH    , UVRAG   , ELMO2   , ARHGAP6 , EVL     , ERRFI1  , ADAM10  , EFS     , SHANK2  , USP8    , ADAM9   , PLSCR1  , CTTNBP2 , DNAJC6  , PTPN6   , FUT8    , ARHGAP1
20 PPFIA2, DLG1  , ACTN2 , PLS3  , GIT1  , ACTN1 , ACTB  , ERC1  , RIMS1 , DBNL  , ACTG1

In [84]:
psi_corr_df_temp <- psi_corr_df %>%
    dplyr::group_by(Gene) %>%
    slice_max(abs(`Micro/PVM`), with_ties=FALSE)
fgsea_stats <- psi_corr_df_temp$`Micro/PVM`
names(fgsea_stats) <- psi_corr_df_temp$Gene
fgsea_stats <- sort(abs(fgsea_stats), decreasing=TRUE)
fgsea_res <- fgsea(pathways=gs_GO_list, stats=fgsea_stats, scoreType="pos")
head(fgsea_res[order(fgsea_res$padj),], 20)

Warning message in preparePathwaysAndStats(pathways, stats, minSize, maxSize, gseaParam, :
“There are ties in the preranked stats (0.42% of the list).
The order of those tied genes will be arbitrary, which may produce unexpected results.”

   pathway
1  GOMF_IMMUNE_RECEPTOR_ACTIVITY
2  GOBP_MYELOID_CELL_ACTIVATION_INVOLVED_IN_IMMUNE_RESPONSE
3  GOBP_INTERLEUKIN_1_PRODUCTION
4  GOBP_POSITIVE_REGULATION_OF_ENDOCYTOSIS
5  GOBP_INTERLEUKIN_6_PRODUCTION
6  GOBP_POSITIVE_REGULATION_OF_PHAGOCYTOSIS
7  GOBP_INTERLEUKIN_1_BETA_PRODUCTION
8  GOBP_INTERLEUKIN_8_PRODUCTION
9  GOBP_REGULATION_OF_B_CELL_DIFFERENTIATION
10 GOBP_REGULATION_OF_PHAGOCYTOSIS
11 GOBP_LEUKOCYTE_MEDIATED_CYTOTOXICITY
12 GOBP_POSITIVE_REGULATION_OF_INTERLEUKIN_2_PRODUCTION
13 GOBP_POSITIVE_REGULATION_OF_INTERLEUKIN_8_PRODUCTION
14 GOMF_TRANSMEMBRANE_TRANSPORTER_BINDING
15 GOBP_NEGATIVE_REGULATION_OF_IMMUNE_EFFECTOR_PROCESS
16 GOBP_NEGATIVE_REGULATION_OF_LYMPHOCYTE_ACTIVATION
17 GOBP_POSITIVE_REGULATION_OF_MYELOID_LEUKOCYTE_DIFFERENTIATION
18 GOBP_POSITIVE_REGULATION_OF_TUMOR_NECROSIS_FACTOR_SUPERFAMILY_CYTOKINE_PRODUCTION
19 GOBP_FC_RECEPTOR_SIGNALING_PATHWAY
20 GOBP_PHAGOCYTOSIS_ENGULFMENT
   pval         padj         log2err   ES        NES      size
1  1.026091e-09 8.070205e-06 0.7881868 0.5603535 1.974241  89
2  2.286129e-09 8.990201e-06 0.7749390 0.5865727 2.009276  66
3  4.659098e-09 9.160952e-06 0.7614608 0.5724394 1.988202  75
4  3.759426e-09 9.160952e-06 0.7614608 0.5281949 1.883397 108
5  7.039346e-09 1.107289e-05 0.7614608 0.5439893 1.916586  89
6  1.830172e-08 2.399050e-05 0.7337620 0.6061633 2.028556  52
7  2.193604e-08 2.464671e-05 0.7337620 0.5795865 1.978352  63
8  2.557038e-08 2.513888e-05 0.7337620 0.6207412 2.056218  48
9  3.939295e-08 3.098256e-05 0.7195128 0.7774474 2.285097  20
10 3.574068e-08 3.098256e-05 0.7195128 0.5612126 1.943578  73
11 8.966156e-08 6.410802e-05 0.7049757 0.5338734 1.869411  83
12 4.640324e-07 2.846023e-04 0.6749629 0.7125046 2.156961  24
13 4.895747e-07 2.846023e-04 0.6594444 0.6367933 2.035136  37
14 5.066030e-07 2.846023e-04 0.6594444 0.4909095 1.740374 100
15 6.428295e-07 3.218033e-04 0.6594444 0.5093996 1.784593  84
16 7.024288e-07 3.218033e-04 0.6594444 0.4968242 1.757808  97
17 6.768862e-07 3.218033e-04 0.6594444 0.6146779 1.980916  39
18 7.364855e-07 3.218033e-04 0.6594444 0.5349248 1.850738  72
19 9.326477e-07 3.860671e-04 0.6594444 0.5921481 1.947189  45
20 1.001097e-06 3.936814e-04 0.6435518 0.6281124 2.007393  37
   leadingEdge
1  LILRB1  , LILRA2  , CMKLR1  , FCGR1BP , FCGR2A  , IL10RA  , CD74    , CSF2RA  , FCAR    , LILRA6  , FPR1    , IL1R1   , LILRB5  , LILRB2  , HLA-DQB1, LILRB4  , IL15RA  , LILRA1  , FCGR2B  , CTSH    , CD4     , FCMR    , IL13RA1 , IL11RA  , IFNGR1  , FCER1G  , IL17RC  , IL1RAP  , FPR2    , GHR     , IL18RAP , CD44    , IL1RL1  , KIR2DL4 , EPOR    , IL18R1  , FCER2   , GPR17   , IL10RB  , LILRA5  , MR1
2  CD84   , ITGAM  , SYK    , MILR1  , LILRA2 , DOCK2  , PTPN6  , TREM2  , PIK3CG , ITGB2  , PLCG2  , ADGRE2 , LGALS9 , FES    , STXBP2 , MYD88  , HAVCR2 , FER    , GATA1  , TYROBP , LAT2   , FCER1G , NMI    , RABGEF1
3  CLEC7A  , CD33    , LILRA2  , NLRC4   , GHRL    , TMEM106A, CASP8   , TREM2   , LGALS9  , CEACAM1 , CARD8   , CASP1   , NLRP1   , TLR6    , RELA    , IFI16   , MYD88   , LILRB4  , HAVCR2  , FOXP1   , ANXA1   , TYROBP  , IGF1    , NLRP3   , MALT1   , APP     , MEFV    , HDAC3   , NAIP    , NOD1    , ERRFI1  , GSTP1   , ARRB2   , LILRA5  , TRIM16  , TMED10  , NLRP12  , IL16
4  CLEC7A , BIN1   , SYK    , CD300LF, C2     , FCGR1BP, DOCK2  , ARAP1  , FCGR2A , TREM2  , PTPRC  , PLCG2  , AXL    , TBC1D5 , AHI1   , NCKAP1L, FLOT1  , AP2M1  , CDC42  , SLC11A1, ANXA2  , IL15RA , FCGR2B , SGIP1  , ANO6   , C4B    , MYO18A , HFE    , DAB2   , PPP3CA , AP2B1  , GH1    , FCER1G , ITGA2  , CALR   , ANGPT1 , FPR2   , SELE   , VEGFA  , APP    , FMR1   , MERTK  , PPT1   , AP2A1  , ARRB2  , ITSN1  , CYBA   , MAGI2  , PPP3CC , TFR2   , CD47   , FCGR2C , RAP1A  , STAT3
5  CLEC7A  , SYK     , LILRA2  , PTPN6   , GHRL    , TMEM106A, TLR1    , CD74    , TLR2    , TREM2   , POU2F2  , PLCG2   , LGALS9  , IRAK3   , LILRB2  , NCKAP1L , TLR6    , RELA    , MYD88   , LILRB4  , HYAL2   , HAVCR2  , BANK1   , TYROBP  , FCER1G  , IL17RC  , RIGI    , IL1RAP  , RABGEF1 , PTPN22  , APP     , BSG     , NOD1    , ZBTB20  , ARRB2   , LILRA5  , CYBA    , TRPV4   , HSPD1   , NLRP12  , IL16    , CD47    , CSK     , IL6
6  CLEC7A , CD300LF, C2     , FCGR1BP, DOCK2  , ARAP1  , FCGR2A , TREM2  , PTPRC  , PLCG2  , NCKAP1L, SLC11A1, IL15RA , FCGR2B , ANO6   , C4B    , MYO18A , FCER1G , ITGA2  , CALR   , FPR2
7  CLEC7A  , CD33    , LILRA2  , NLRC4   , GHRL    , TMEM106A, CASP8   , TREM2   , LGALS9  , CARD8   , CASP1   , NLRP1   , TLR6    , RELA    , IFI16   , MYD88   , LILRB4  , FOXP1   , TYROBP  , IGF1    , NLRP3   , MALT1   , APP     , MEFV    , NAIP    , NOD1    , ERRFI1  , GSTP1   , ARRB2   , LILRA5  , TRIM16
8  CLEC7A, CD33  , SYK   , LILRA2, TLR5  , TLR1  , CD74  , TLR2  , PTPRC , LGALS9, RIPK1 , TLR6  , RELA  , MYD88 , HYAL2 , PRKD2 , ANXA1
9  SYK    , PTPN6  , SLAMF8 , CARD11 , IL4I1  , NCKAP1L, IL7    , PCID2  , MMP14  , STAT5A , ZFP36L1
10 CLEC7A , SYK    , CD300LF, C2     , FCGR1BP, DOCK2  , ARAP1  , FCGR2A , HCK    , TLR2   , TREM2  , PTPRC  , PLCG2  , PLSCR1 , NCKAP1L, SLC11A1, IL15RA , FCGR2B , ANO6   , C4B    , MYO18A , SYT7   , FCER1G , ITGA2  , CALR   , FPR2   , RACK1  , SCARB1 , MERTK
11 ITGAM  , LILRB1 , IL18   , FCGR1BP, VAV1   , PTPN6  , CTSC   , FCGR2A , PTPRC  , NCF1   , PIK3R6 , LGALS9 , CEACAM1, CYRIB  , STXBP2 , NCKAP1L, MYD88  , HAVCR2 , STAT5A , FCGR2B , CTSH   , TREM1  , CD1D   , TYROBP
12 CD86  , CLEC7A, RUNX1 , CARD11, PTPRC , PLCG2 , PRKD2 , STAT5A, CD4   , ANXA1
13 CLEC7A, SYK   , LILRA2, TLR5  , TLR1  , CD74  , TLR2  , LGALS9, RIPK1 , RELA  , MYD88 , HYAL2 , PRKD2
14 BAK1    , KCNQ1   , KCNE3   , AP2M1   , AKAP6   , CTNNB1  , KCNC1   , KCNIP2  , FHL1    , SLC8A1  , STX1A   , PKD1    , NEDD4   , ACTN1   , WWP2    , PKD2    , ITPR2   , FGF12   , CRBN    , ANK3    , KCNE1   , RIMS2   , CBARP   , TRPC1   , KCNAB1  , HAP1    , TRAPPC2 , ANK2    , USP10   , CAMK2D  , FMR1    , TRDN    , ABCC9   , KCNAB2  , DPP10   , ATP2A3  , GRINA   , SCN3B   , CDH5    , ASPH    , FYN     , FLNA    , HSP90AA1, ABCC8   , KCNH5   , DLG1    , FKBP1A  , GPD1L   , OXSR1   , KCNC2   , SCN1B   , AKAP9   , YWHAZ   , ACTN2   , SRC
15 CD84    , LILRB1  , PTPN6   , SLAMF8  , PTPRC   , IL4I1   , LGALS9  , AXL     , SERPING1, CEACAM1 , IRAK3   , VSIG4   , NCKAP1L , LILRB4  , HAVCR2  , JAK3    , STAT5A  , FCGR2B  , HFE     , ANXA1   , FER     , TMBIM6  , CD46    , RABGEF1 , ANGPT1
16 CD86     , LILRB1   , PTPN6    , RUNX1    , CD74     , IL4I1    , LGALS9   , AXL      , LST1     , VSIG4    , LILRB2   , LILRB4   , HAVCR2   , SCRIB    , JAK3     , PRKAR1A  , IRF1     , STAT5A   , FCGR2B   , HFE      , ANXA1    , TNFRSF13B, TMEM131L , BANK1    , PELI1    , TYROBP   , PTPN2    , PKN1     , BTN2A2   , PTPN22   , ITCH     , CD37     , MERTK    , ATM      , CD274    , TBC1D10C , PLA2G2D  , ERBB2    , CLEC12A  , CLEC4G   , CSK      , DLG1     , IL4R     , IL2RA
17 RUNX1  , CD74   , CASP8  , TREM2  , FES    , RIPK1  , LIF    , CREB1  , DCSTAMP, STAT5A , PRKCA  , CD4    , PPP3CA , ZFP36L1, TYROBP
18 CD86    , CLEC7A  , SYK     , LILRA2  , FCGR1BP , TMEM106A, FCGR2A  , TLR1    , TLR2    , PTPRC   , PLCG2   , LGALS9  , RIPK1   , MYD88   , HAVCR2  , FCGR2B  , NRDC    , TNFRSF8 , PSEN1   , IFNGR1  , TYROBP  , FCER1G  , RIGI    , ARFGEF2 , OAS1    , APP     , OAS2    , NOD1    , LY96    , ZBTB20  , OAS3    , LILRA5  , CYBA    , ABCC8   , IL6     , FCGR2C
19 CD33   , SYK    , FCGR1BP, VAV1   , FCGR2A , HCK    , FCAR   , PLCG2  , MYO1G  , MAPK10 , PTK2   , FCGR2B , FCMR   , PRKCD  , FER    , FCER1G , MAP2K4 , MAPK9  , CLEC4E , FCER2  , PLCG1  , IKBKB  , FYN
20 MSR1    , ITGAM   , TREM2   , BIN2    , ITGB2   , TIMD4   , PLCG2   , ARHGAP25, NCKAP1L , CDC42   , BECN1   , FCGR2B  , ANO6    , GSN     , FCER1G  , ITGA2

In [86]:
psi_corr_df_temp <- psi_corr_df %>%
    dplyr::group_by(Gene) %>%
    slice_max(abs(`Astro`), with_ties=FALSE)
fgsea_stats <- psi_corr_df_temp$`Astro`
names(fgsea_stats) <- psi_corr_df_temp$Gene
fgsea_stats <- sort(abs(fgsea_stats), decreasing=TRUE)
fgsea_res <- fgsea(pathways=gs_GO_list, stats=fgsea_stats, scoreType="pos")
head(fgsea_res[order(fgsea_res$padj),], 20)

Warning message in preparePathwaysAndStats(pathways, stats, minSize, maxSize, gseaParam, :
“There are ties in the preranked stats (0.47% of the list).
The order of those tied genes will be arbitrary, which may produce unexpected results.”

   pathway                                                       pval
1  GOBP_CYTOKINESIS                                              3.091404e-10
2  GOBP_CELLULAR_RESPONSE_TO_FLUID_SHEAR_STRESS                  1.966396e-09
3  GOBP_PRESYNAPTIC_ENDOCYTOSIS                                  2.791441e-08
4  GOBP_SYNAPTIC_VESICLE_RECYCLING                               2.453200e-08
5  GOBP_NEUROTRANSMITTER_SECRETION                               3.626243e-08
6  GOBP_ACTIN_FILAMENT_BUNDLE_ORGANIZATION                       4.826277e-08
7  GOBP_POSITIVE_REGULATION_OF_SUPRAMOLECULAR_FIBER_ORGANIZATION 5.087154e-08
8  GOBP_CYTOSKELETON_DEPENDENT_CYTOKINESIS                       7.812630e-08
9  GOBP_RESPONSE_TO_FLUID_SHEAR_STRESS                           8.651558e-08
10 GOBP_POSITIVE_REGULATION_OF_CYTOSKELETON_ORGANIZATION         1.612395e-07
11 GOBP_POSITIVE_REGULATION_OF_SYNAPTIC_TRANSMISSION             1.359475e-07
12 GOBP_PROTEIN_LOCALIZATION_TO_CELL_JUNCTION                    1.528088e-07
13 GOBP_REGULATION_OF_POSTSYNAPSE_ORGANIZATION                   2.986545e-07
14 GOBP_CLATHRIN_DEPENDENT_ENDOCYTOSIS                           3.537247e-07
15 GOBP_DENDRITE_MORPHOGENESIS                                   3.918503e-07
16 GOBP_CELL_SUBSTRATE_JUNCTION_ORGANIZATION                     4.895747e-07
17 GOBP_VESICLE_DOCKING                                          4.810606e-07
18 GOMF_CALCIUM_ION_TRANSMEMBRANE_TRANSPORTER_ACTIVITY           7.194572e-07
19 GOBP_DENDRITIC_SPINE_DEVELOPMENT                              7.705423e-07
20 GOBP_PROTEIN_DEPOLYMERIZATION                                 8.641985e-07
   padj         log2err   ES        NES      size
1  2.431389e-06 0.8140358 0.6021901 1.672272 139
2  7.732852e-06 0.7749390 0.8392109 2.049546  23
3  5.488671e-05 0.7337620 0.6510486 1.753961  69
4  5.488671e-05 0.7337620 0.6519013 1.758793  73
5  5.704081e-05 0.7195128 0.5922366 1.631073 115
6  5.715781e-05 0.7195128 0.5791737 1.598690 123
7  5.715781e-05 0.7195128 0.5789262 1.598007 123
8  7.560500e-05 0.7049757 0.6059256 1.656310  95
9  7.560500e-05 0.7049757 0.7723224 1.939577  30
10 1.056791e-04 0.6901325 0.5602074 1.552731 133
11 1.056791e-04 0.6901325 0.5823447 1.603020 114
12 1.056791e-04 0.6901325 0.6082876 1.653959  89
13 1.806860e-04 0.6749629 0.5947962 1.625888  95
14 1.987175e-04 0.6749629 0.6949004 1.801086  42
15 2.054602e-04 0.6749629 0.5902960 1.617792 103
16 2.265003e-04 0.6594444 0.6127830 1.655627  77
17 2.265003e-04 0.6594444 0.6835333 1.775719  43
18 3.143628e-04 0.6594444 0.5534727 1.531329 130
19 3.189640e-04 0.6594444 0.6183226 1.665796  69
20 3.398460e-04 0.6594444 0.5921228 1.615174  92
   leadingEdge
1  EXOC7    , FMN2     , PLEC     , SH3GLB1  , RAB11FIP3, ACTR2    , MYH10    , PRPF40A  , MYH14    , ROCK1    , WNK1     , GIT1     , MYH9     , SPIRE1   , EXOC6B   , INCENP   , MTMR3    , IQGAP1   , SEPTIN2  , NUP62    , PKN2     , KIF13A   , CSPP1    , DCTN3    , ANK3     , SEPTIN11 , SEPTIN6  , CIT      , CENPV    , EXOC1    , SEPTIN4  , AHCTF1   , PKP4     , MITD1    , CCP110   , SPAST    , SPART    , RHOA     , SNX9     , CDC25B   , CALM2    , USP8     , CDC42    , ECT2     , MYO19    , CHMP7    , CHMP1A   , TRIM36   , ANXA11   , APC      , GIPC1    , CCDC66   , IST1     , CALM1    , SEPTIN7  , STAMBP   , CUL7     , KIF23    , BECN1    , KLHDC8B  , CDC14B   , SEPTIN9  , SETD2    , DRD2     , BIRC6    , RACGAP1  , TTC19    , CHMP5
2  PLEC  , PTK2  , SRC   , PKD2  , MEF2C , GNAS  , MTSS1 , PKN2  , ASS1  , PRKACB, AKT1
3  AP2A1  , CLTB   , BLTP1  , CLTA   , TBC1D24, ITSN1  , SGIP1  , DNM2   , AP2B1  , ROCK1  , DNM3   , AP2M1  , SYNJ1  , ITSN2  , BIN1   , PPP3CC , NLGN3  , ATP8A1 , SCRIB  , GAK    , PPP3CB , AMPH   , DNM1   , AP1G1  , SNX9   , CALM2  , MYLK   , AP3B2  , SYT7   , AP2A2  , DGKQ   , ACTG1  , PIP5K1C, AAK1   , CALM1
4  AP2A1  , CLTB   , BLTP1  , CLTA   , TBC1D24, ITSN1  , SGIP1  , DNM2   , AP2B1  , ROCK1  , GIT1   , GIT2   , DNM3   , AP2M1  , SYNJ1  , ITSN2  , BIN1   , PPP3CC , NLGN3  , ATP8A1 , SCRIB  , GAK    , PPP3CB , AMPH   , DNM1   , AP1G1  , SNX9   , GRIPAP1, MYLK   , AP3B2  , SYT7   , AP2A2  , DGKQ   , ACTG1  , PIP5K1C
5  UNC13B  , CADPS2  , RAB3GAP1, NRXN1   , PNKD    , MEF2C   , AP2B1   , SNAP23  , GIT1    , NRXN2   , PPFIA3  , DNAJC5  , CASK    , ATP2A2  , SYNJ1   , PPFIA2  , NF1     , SCRIB   , PPP3CA  , PDZD11  , TSPOAP1 , CADPS   , STX2    , UNC13A  , STXBP5  , RIMS1   , CAMK2A  , DVL1    , PCLO    , NAPB    , BLOC1S6 , STXBP1  , RAP1A   , RIMS2   , SYT1    , CACNB4  , LIN7A   , GGCX    , FMR1    , SYT7    , DYSF    , PIP5K1C , SV2B    , BRSK1   , SNAP25  , PPT1    , ERC2    , SNCAIP  , STX1A   , PRKCG   , GRM4    , PREPL   , SYT5    , SNAP47  , KMO     , SNCA    , ABCC8   , MICU3
6  SORBS1   , FMN2     , CD47     , ADD1     , ARHGEF10L, CLASP1   , LIMCH1   , PPFIA1   , DNM2     , SRC      , ACTN1    , ROCK1    , TPM1     , PLS3     , CARMIL1  , SPIRE1   , CALD1    , CLASP2   , NF2      , FLNA     , ZYX      , MYO1B    , MTSS1    , LIMA1    , FERMT2   , ARRB1    , PDCD10   , PHLDB2   , PHACTR1  , DMTN     , MET      , RHOA     , PXN      , BLOC1S6  , CDC42    , CCDC88A  , INPP5K   , ARAP1    , EPHA1    , TTC8     , ACTG1    , EVL      , PAK1     , RAPGEF3  , PLS1     , FHOD1    , TJP1     , SHROOM1  , SHANK1   , FAM171A1 , ADD2     , ITGB1BP1
7  PDE4DIP  , ABI2     , CLIP1    , NUMA1    , CD47     , ARHGEF10L, CLASP1   , MAPT     , LIMCH1   , NCKAP1   , DCTN1    , DLG1     , TPM1     , APP      , GIT1     , CARMIL1  , CTTN     , NF2      , FLNA     , BIN1     , FCHSD2   , GSN      , MTSS1    , SLAIN1   , FERMT2   , CKAP5    , FES      , SPAST    , MET      , RHOA     , SNX9     , PXN      , CLU      , USP8     , CDC42    , CCDC88A  , PRKD1    , NPHS1    , EPHA1    , NAV3     , CDK5RAP2 , EVL      , PAK1     , ACTN2    , RAPGEF3  , FHOD1
8  EXOC7    , FMN2     , PLEC     , RAB11FIP3, ACTR2    , MYH10    , MYH14    , ROCK1    , WNK1     , SPIRE1   , EXOC6B   , INCENP   , MTMR3    , IQGAP1   , SEPTIN2  , NUP62    , DCTN3    , ANK3     , SEPTIN11 , SEPTIN6  , CIT      , EXOC1    , SEPTIN4  , MITD1    , SPAST    , SPART    , RHOA     , SNX9     , USP8     , ECT2     , CHMP7    , CHMP1A   , TRIM36   , APC      , IST1     , SEPTIN7  , STAMBP   , CUL7
9  PLEC  , PTK2  , SRC   , PKD2  , MEF2C , GNAS  , PKD1  , MTSS1 , PKN2  , ASS1  , PRKACB, AKT1
10 PDE4DIP  , ABI2     , CLIP1    , NUMA1    , CD47     , ARHGEF10L, CLASP1   , MAPT     , LIMCH1   , NCKAP1   , DCTN1    , DLG1     , TPM1     , GIT1     , CARMIL1  , CTTN     , NF2      , FLNA     , POC1B    , ADD3     , BIN1     , FCHSD2   , GSN      , NUP62    , MTSS1    , SLAIN1   , FERMT2   , CKAP5    , FES      , SPAST    , MET      , RHOA     , SNX9     , PXN      , CDC42    , CCDC88A  , PRKD1    , NPHS1    , EPHA1    , NAV3     , CDK5RAP2 , EVL      , PAK1     , ACTN2    , RAPGEF3  , FHOD1
11 CAMK2G  , CAMK2B  , CLSTN1  , RAB3GAP1, NRXN1   , HDAC6   , CAMK2D  , ADORA1  , APP     , FXR1    , IQSEC2  , DLG4    , STX3    , NF1     , NLGN3   , STAU1   , PPP3CA  , ARRB2   , CAMK2A  , GRIA3   , CALM2   , NPTN    , STXBP1  , GRIN1   , SLC1A3  , SLC8A3  , NMU     , SYT1    , SLC24A2 , GSK3B   , FLOT1   , LAMA2   , FMR1    , CALM1   , CREB1   , SNAP25  , LGI1    , PRKCZ   , CRHR2   , RAPSN   , STX1A   , PRKCG   , MPP2    , RELN    , SHANK2  , CHRNA7  , KMO     , EIF2AK4 , DRD2    , SNCA    , NTRK2   , SQSTM1  , GRIN2B  , MICU3   , NALCN   , LARGE1  , PRRT1   , GRIN2A  , GRIK2   , BRAF    , RETN    , NSG1    , LILRB2  , LGMN    , BAIAP3  , EPHA4   , TNR     , SHISA7  , SYT12   , NTRK1   , NCSTN
12 CLSTN1  , GPHN    , CTNND1  , MAPT    , NRXN1   , DLG1    , DLG3    , GIT1    , NRXN2   , MAPK8IP3, FLNA    , EPB41L3 , IQSEC2  , DLG4    , STX3    , STAU1   , FERMT2  , SCRIB   , MAPK9   , ARHGAP44, DVL1    , VPS35   , PCLO    , ERBB2   , LRRC7   , RAP1A   , KIF3A   , GRIPAP1 , CACNA2D2, GRIP1   , STAU2   , KIF5A   , NPHS1   , ERBB4   , ACTG1   , LGI1    , RAPSN   , LAMTOR3 , RELN    , TJP1    , RAB27B  , SHANK1  , JAK1    , ADAM10
13 NRCAM   , ABI2    , PTPRS   , CAMK2B  , DBN1    , SIPA1L1 , ITSN1   , CYFIP2  , DOCK4   , APP     , CAPRIN2 , NRXN2   , PTPRD   , PPFIA2  , RTN4    , KIF1A   , NF1     , PLPPR4  , NAE1    , AKT1    , MARK1   , ARHGAP44, DVL1    , VPS35   , PUM2    , DOCK10  , NCKIPSD , CDC42   , ELMO1   , ZMYND8  , TANC2   , STAU2   , ARHGAP12, PAK3    , ABHD17A , NEDD8   , CDH2    , RELN    , LRP8    , GPRASP3 , LATS1   , SRCIN1  , ADAM10  , FGFR1   , GRIN2B  , DISC1   , RAC1    , SLC12A5 , NUMBL   , CC2D1A  , LILRB2  , PDLIM5  , SENP1   , PSEN1   , EPHA4   , ARHGAP33
14 AP2A1  , SNAP91 , CLTB   , PICALM , CLTC   , CLTA   , ITSN1  , SGIP1  , AP2B1  , AP2M1  , ITSN2  , SCYL2  , FCHSD2 , MAGI2  , GAK    , SMAP1  , DNM1   , TNK2   , AP2A2  , LMBRD1 , SH3GL3 , PIP5K1C, AAK1   , STON2  , INPP5F , HIP1R  , CANX
15 ABI2     , CAMK2B   , DBN1     , MINK1    , PICALM   , SIPA1L1  , TBC1D24  , HDAC6    , NSMF     , PARP6    , KIDINS220, CAPRIN2  , ABI1     , MEF2A    , PTPRD    , CTNNA2   , DLG4     , PPFIA2   , KIF1A    , CDKL3    , MAP2     , ATG16L1  , PPP3CA   , VLDLR    , ARHGAP44 , DVL1     , PHACTR1  , RAPGEF2  , TRAK1    , TNIK     , HECW1    , DOCK10   , NEDD4    , CDC42    , GSK3B    , TANC2    , CHRNB2   , ELAVL4   , SS18L1   , STAU2    , HECW2    , CTNND2   , KNDC1    , PAK3     , CUL7     , NEDD4L   , RELN     , LRP8     , GPRASP3  , SHANK1   , CHRNA7   , SRCIN1   , RAC1     , SULT4A1
16 MACF1  , SORBS1 , PLEC   , PTK2   , DST    , CLASP1 , ARHGEF7, PTPRK  , LIMCH1 , SRC    , ACTN1  , ROCK1  , MAP4K4 , CTTN   , CLASP2 , FERMT2 , PTPRA  , PHLDB2 , DMTN   , GPM6B  , RHOA   , VEGFA  , ACTG1  , IQSEC1 , TNS1   , SLK    , TRIP6  , ACTN2
17 UNC13B , EXOC7  , NDRG4  , STX16  , PPFIA3 , EXOC6B , USO1   , STX3   , VTI1B  , STX2   , RABEPK , UNC13A , RIMS1  , EXOC1  , BLOC1S6, SYTL2  , STXBP1 , RIMS2  , SYT1
18 ATP2B1  , ATP2B4  , CACNB1  , GPM6A   , NRXN1   , RYR1    , YWHAE   , PKD2    , RYR3    , STIM2   , NRXN2   , PKD1    , ATP2A2  , STIM1   , MICU1   , CACNA2D3, GRIK1   , ATP2B2  , TMBIM6  , CACNA1D , TSPOAP1 , CACNA1C , CACNA1A , CACNA1G , GRIA3   , CALM2   , RYR2    , MICU2   , GRIN1   , SLC8A3  , CACNB4  , SLC8A1  , CACNA2D2, SLC24A2 , P2RX4   , CACNB3  , CACNA1S , ITPR1   , ATP2C1  , CALM1   , CACNA2D1, CACNB2  , TRPM2   , STX1A   , TRPM3   , PHPT1   , TRPM4   , CHRNA7  , TMC1    , CNGB1   , GRIN2B  , MICU3   , CACNA1E , SLC8B1  , GRIN2A  , GRM3    , ATP2C2  , FAIM2   , ATP2A1  , FKBP1B  , GRIK2   , TPCN1   , ATP2B3
19 ABI2    , PTPRS   , CAMK2B  , DBN1    , SIPA1L1 , ITSN1   , HDAC6   , MEF2C   , GIT1    , CAPRIN2 , PAK4    , PTPRD   , DLG4    , PPFIA2  , KIF1A   , CAMK2A  , ARHGAP44, DVL1    , DOCK10  , CDC42   , ZMYND8  , MAPKAPK5, TANC2   , FMR1    , STAU2   , CTNND2  , IQSEC1  , PAK3    , RELN    , LRP8    , GPRASP3 , SHANK1  , SRCIN1  , DISC1   , RAC1    , SLC12A5 , SDK1    , PDLIM5  , DIP2A   , CAMK1   , PSEN1   , EPHA4   , ARHGAP33
20 SPTAN1 , CAPZB  , ADD1   , KIF21A , CLTC   , CLASP1 , ASPH   , KIF2A  , HDAC6  , TWF1   , CAMSAP2, CARMIL1, CLASP2 , MICAL3 , SYNJ1  , ADD3   , GSN    , LIMA1  , GAK    , CKAP5  , ATXN7  , STMN4  , SPAST  , DMTN   , APC    , NAV3   , MID1   , MID1IP1, ACTN2  , ASB2   , BBOF1