In [120]:
# conda activate genomic_tools

library(ensembldb)
library(data.table)
library(GenomicRanges)
library(EnsDb.Hsapiens.v86)

In [121]:
# Compile list of all exons from cell type splicing analysis
exon_lookup <- list()
for (file in list.files("data/ctype_exons")) {
    if (grepl("csv$", file)) {
        signif_exons_df <- fread(paste0("data/ctype_exons/", file), data.table=FALSE)
        signif_exons_df <- signif_exons_df[!is.na(signif_exons_df[['Oligo']]), ]
        for (i in 1:nrow(signif_exons_df)) {
            row <- signif_exons_df[i, ]
            event <- as.character(row[1])
            if (event %in% names(exon_lookup)) {
                next
            }
            exon_lookup[[event]] <- data.frame(
                    gene=row['Gene'],
                    chr=row['chr'],
                    strand=row['strand'],
                    exon_start=row['exon_start'],
                    exon_end=row['exon_end']
                )
        } 
    }
}

In [172]:
library(AnnotationHub)
ah <- AnnotationHub()
query(ah, c("EnsDb", "Hsapiens", "108"))

ERROR: Error in library(AnnotationHub): there is no package called 'AnnotationHub'

In [122]:
exon_df <- do.call(rbind, exon_lookup)

In [124]:
exon_df_subset <- exon_df[1:10, ]

In [125]:
exon_gr <- GRanges(
    seqnames=sapply(strsplit(x = exon_df_subset$chr, split="chr"), function(x) x[2]),
    ranges=IRanges(start=exon_df_subset$exon_start, end=exon_df_subset$exon_end),
    names=rownames(exon_df_subset),
    strand=strand(exon_df_subset$strand)
)

In [128]:
db <- EnsDb.Hsapiens.v86
db_filtered <- filter(db, filter=TxBiotypeFilter("protein_coding"))

In [ ]:
g2p <- genomeToProtein(exon_gr_clipped, db_filtered)
g2p_df <- as.data.frame(g2p)
head(g2p_df)

Warning message:
"Provided coordinates for 'ENST00000314070', 'ENST00000462234', 'ENST00000376460', 'ENST00000629219' are not within the coding region"
Warning message:
"The CDS of 'ENST00000446759', 'ENST00000339554' does not match the length of the encoded protein. Returned protein coordinates for this/these transcript(s) might not be correct"

   group group_name start end  width names           tx_id           cds_ok
1   1    NA           15    65 51    ENSP00000403049 ENST00000446759 FALSE
2   2    NA           -1    -1  1                    ENST00000376460    NA
3   3    NA         1790  1791  2    ENSP00000365643 ENST00000376460  TRUE
4   3    NA         1790  1791  2    ENSP00000406883 ENST00000442173  TRUE
5   4    NA          276   284  9    ENSP00000289290 ENST00000289290  TRUE
6   4    NA          276   284  9    ENSP00000398945 ENST00000420625  TRUE
7   5    NA          143   145  3    ENSP00000444957 ENST00000545766  TRUE
8   6    NA          254   263 10    ENSP00000378338 ENST00000394869  TRUE
9   6    NA          254   263 10    ENSP00000462775 ENST00000581348  TRUE
10  7    NA          783   812 30    ENSP00000360916 ENST00000371850  TRUE
11  7    NA          773   802 30    ENSP00000360917 ENST00000371851  TRUE
12  8    NA          235   258 24    ENSP00000265663 ENST00000265663  TRUE
13  8    NA           70    92 23    ENSP00000342966 ENST00000339554 FALSE
14  8    NA          235   258 24    ENSP00000360527 ENST00000371472  TRUE
15  8    NA          237   260 24    ENSP00000360528 ENST00000371473  TRUE
16  8    NA          237   260 24    ENSP00000360530 ENST00000371475  TRUE
17  9    NA          235   237  3    ENSP00000360528 ENST00000371473  TRUE
18  9    NA          235   237  3    ENSP00000360530 ENST00000371475  TRUE
19  9    NA          235   237  3    ENSP00000412007 ENST00000437259  TRUE
20 10    NA           -1    -1  1                    ENST00000629219    NA
   exon_id         exon_rank seq_start seq_end   seq_name seq_strand
1  ENSE00003461009  3         77743016  77743165 13       +
2  ENSE00001607866 56         98796206  98796213 13       -
3  ENSE00001742044 49         98809123  98809128 13       -
4  ENSE00001742044 49         98809123  98809128 13       -
5  ENSE00001947677 10        115640110 115640136 X        +
6  ENSE00001947677  8        115640110 115640136 X        +
7  ENSE00003743980  5         15828192  15828200 X        -
8  ENSE00003498768  8         29578962  29578988 17       -
9  ENSE00003498768  8         29578962  29578988 17       -
10 ENSE00001096231 28        133769417 133769503 9        -
11 ENSE00001096231 26        133769417 133769503 9        -
12 ENSE00001738815  5        137455239 137455307 9        -
13 ENSE00001738815  3        137455239 137455307 9        -
14 ENSE00001738815  5        137455239 137455307 9        -
15 ENSE00001738815  6        137455239 137455307 9        -
16 ENSE00001738815  6        137455239 137455307 9        -
17 ENSE00002404248  5        137455629 137455634 9        -
18 ENSE00002404248  5        137455629 137455634 9        -
19 ENSE00002404248  5        137455629 137455634 9        -
20 ENSE00003760529  2        158533438 158533467 2        +

In [ ]:
colnames(g2p_df)[ncol(g2p_df)] <- "event"  
exon_df$event = rownames(exon_df)

In [155]:
merge(g2p_df, exon_df, by.x="event", by.y="event", all.x=TRUE)

   event                           group group_name start end  width
1  ENSG00000088387_ProteinCoding_1  1    NA           -1    -1  1
2  ENSG00000088387_ProteinCoding_3  3    NA         1790  1791  2
3  ENSG00000088387_ProteinCoding_3  3    NA         1790  1791  2
4  ENSG00000102024_ProteinCoding_2  8    NA          276   284  9
5  ENSG00000102024_ProteinCoding_2  8    NA          276   284  9
6  ENSG00000108262_ProteinCoding_1  4    NA          254   263 10
7  ENSG00000108262_ProteinCoding_1  4    NA          254   263 10
8  ENSG00000139737_ProteinCoding_1  9    NA           15    65 51
9  ENSG00000144283_NMD_2            7    NA           -1    -1  1
10 ENSG00000160293_ProteinCoding_1 10    NA          783   812 30
11 ENSG00000160293_ProteinCoding_1 10    NA          773   802 30
12 ENSG00000165802_ProteinCoding_3  5    NA          235   258 24
13 ENSG00000165802_ProteinCoding_3  5    NA           70    92 23
14 ENSG00000165802_ProteinCoding_3  5    NA          235   258 24
15 ENSG00000165802_ProteinCoding_3  5    NA          237   260 24
16 ENSG00000165802_ProteinCoding_3  5    NA          237   260 24
17 ENSG00000165802_ProteinCoding_4  6    NA          235   237  3
18 ENSG00000165802_ProteinCoding_4  6    NA          235   237  3
19 ENSG00000165802_ProteinCoding_4  6    NA          235   237  3
20 ENSG00000182287_ProteinCoding_1  2    NA          143   145  3
   names.x         tx_id           cds_ok exon_id         exon_rank seq_start
1                  ENST00000376460    NA  ENSE00001607866 56         98796206
2  ENSP00000365643 ENST00000376460  TRUE  ENSE00001742044 49         98809123
3  ENSP00000406883 ENST00000442173  TRUE  ENSE00001742044 49         98809123
4  ENSP00000289290 ENST00000289290  TRUE  ENSE00001947677 10        115640110
5  ENSP00000398945 ENST00000420625  TRUE  ENSE00001947677  8        115640110
6  ENSP00000378338 ENST00000394869  TRUE  ENSE00003498768  8         29578962
7  ENSP00000462775 ENST00000581348  TRUE  ENSE00003498768  8         29578962
8  ENSP00000403049 ENST00000446759 FALSE  ENSE00003461009  3         77743016
9                                     NA  NA              NA        158533438
10 ENSP00000360916 ENST00000371850  TRUE  ENSE00001096231 28        133769417
11 ENSP00000360917 ENST00000371851  TRUE  ENSE00001096231 26        133769417
12 ENSP00000265663 ENST00000265663  TRUE  ENSE00001738815  5        137455239
13 ENSP00000342966 ENST00000339554 FALSE  ENSE00001738815  3        137455239
14 ENSP00000360527 ENST00000371472  TRUE  ENSE00001738815  5        137455239
15 ENSP00000360528 ENST00000371473  TRUE  ENSE00001738815  6        137455239
16 ENSP00000360530 ENST00000371475  TRUE  ENSE00001738815  6        137455239
17 ENSP00000360528 ENST00000371473  TRUE  ENSE00002404248  5        137455629
18 ENSP00000360530 ENST00000371475  TRUE  ENSE00002404248  5        137455629
19 ENSP00000412007 ENST00000437259  TRUE  ENSE00002404248  5        137455629
20 ENSP00000444957 ENST00000545766  TRUE  ENSE00003743980  5         15828192
   seq_end   seq_name seq_strand Gene   chr   strand exon_start exon_end
1   98796213 13       -          DOCK9  chr13 -       98796206   98796213
2   98809128 13       -          DOCK9  chr13 -       98809123   98809128
3   98809128 13       -          DOCK9  chr13 -       98809123   98809128
4  115640136 X        +          PLS3   chrX  +      115640110  115640136
5  115640136 X        +          PLS3   chrX  +      115640110  115640136
6   29578988 17       -          GIT1   chr17 -       29578962   29578988
7   29578988 17       -          GIT1   chr17 -       29578962   29578988
8   77743165 13       +          SLAIN1 chr13 +       77743016   77743165
9  158533534 2        +          PKP4   chr2  +      158533438  158533534
10 133769503 9        -          VAV2   chr9  -      133769417  133769503
11 133769503 9        -          VAV2   chr9  -      133769417  133769503
12 137455307 9        -          NSMF   chr9  -      137455239  137455307
13 137455307 9        -          NSMF   chr9  -      137455239  137455307
14 137455307 9        -          NSMF   chr9  -      137455239  137455307
15 137455307 9        -          NSMF   chr9  -      137455239  137455307
16 137455307 9        -          NSMF   chr9  -      137455239  137455307
17 137455634 9        -          NSMF   chr9  -      137455629  137455634
18 137455634 9        -          NSMF   chr9  -      137455629  137455634
19 137455634 9        -          NSMF   chr9  -      137455629  137455634
20  15828200 X        -          AP1S2  chrX  -       15828192   15828200
   names.y
1  ENSG00000088387_ProteinCoding_1
2  ENSG00000088387_ProteinCoding_3
3  ENSG00000088387_ProteinCoding_3
4  ENSG00000102024_ProteinCoding_2
5  ENSG00000102024_ProteinCoding_2
6  ENSG00000108262_ProteinCoding_1
7  ENSG00000108262_ProteinCoding_1
8  ENSG00000139737_ProteinCoding_1
9  ENSG00000144283_NMD_2
10 ENSG00000160293_ProteinCoding_1
11 ENSG00000160293_ProteinCoding_1
12 ENSG00000165802_ProteinCoding_3
13 ENSG00000165802_ProteinCoding_3
14 ENSG00000165802_ProteinCoding_3
15 ENSG00000165802_ProteinCoding_3
16 ENSG00000165802_ProteinCoding_3
17 ENSG00000165802_ProteinCoding_4
18 ENSG00000165802_ProteinCoding_4
19 ENSG00000165802_ProteinCoding_4
20 ENSG00000182287_ProteinCoding_1

In [ ]:
# Filter to valid mappings for this exon
valid <- g2p_df[g2p_df$start > 0 & !is.na(g2p_df$names), ]

# Get protein sequences
prot_seqs <- proteins(db_filtered,
                      filter=ProteinIdFilter(unique(valid$names)),
                      return.type="AAStringSet")

# Extract subsequences
valid$aa_seq <- mapply(function(prot_id, start, end) {
    as.character(subseq(prot_seqs[prot_id], start=start, end=end))
}, valid$names, valid$start, valid$end)